"""Writes the crit-autofix PR body to stdout. All values from env vars."""
import os, json, pathlib

r = json.loads(pathlib.Path('/tmp/claude_result.json').read_text())
fired_at     = os.environ.get('FIRED_AT', '')
alert_summary = os.environ.get('ALERT_SUMMARY', '')
log_ctx      = os.environ.get('LOG_CTX', '')
run_url      = os.environ.get('RUN_URL', '')
workflow_url = os.environ.get('WORKFLOW_URL', '')
run_number   = os.environ.get('RUN_NUMBER', '')

print(f"""## Auto-fix by Claude

Triggered by Grafana CRIT alert at `{fired_at}`.

**Alert:** {alert_summary}

**Log excerpt:**
```
{log_ctx}
```

---
_Auto-generated by [grafana-crit-fix]({workflow_url}) · run [#{run_number}]({run_url})_""")
