---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: fuzemarket
spec:
  encryptedData:
    .dockerconfigjson: AgDa7Pfk9m+pc1CTrm+yvlPIi/fEAuvkk0cHCQqeLRTib1zmdLo7ddnFTpm4o0nLy4Hl1wY2ghtMu3kJsojiWejgcv4FTJEig1RNWSqG5a/l3sICCIC4+2ruwgQJNlIUUCXz/jXsXsqpFjFvllzse9EBKNKVcVnLxnFwRR5BDqgrsLJqr3qwJcCkjrh/nMSnEh1sa04xgAmox0sr3Gb2UBowduIFmgD99nPw/MJnq3/qdQUZTuQmhGqbByAa/4iLnsFuML2nx1svukrzqbhpF89FZJqk9QBCP/Udbe1sDcE36h3IQabojyfNaLQR65Ut5IQpPb4SMP8p+qmd3fwN+dqP9tmK+iuo6PcPF26DKF4Sn4cLWuJPzIE6o17bmuM8HSg63WBdDE2azlTclwL7ZiMRuM0n/H4FiUorB1WRUC365ynJ1coa8H8uxjvNBW5BIsY99kZb/0arMIE7abo8SRZljYitSxJZllJOxTgZJmna87FYP2iNVwDYDH4P1Y9EX14+WwmJlPuLcGpTlyPejKsg4Zd5KKuzFrOu5Hd55ZYDB+9WnVSUzWb7VjQnWGLCn5BfKBIMAWJi2NZJV53IkVmLAy4mShuSDgQNTRScNUK/UKCWPdqURFqLBhO+O/8dqQQvW7SzEvIdKBMIBWK+p/TYMPD0FFs5acJuFh4xRscF8G8NzHVi3Y0sKUu58tbaY4GWAh+b/V0EsL4vbPbrMWX88ae6XaykOTIF2VSh28NYcGxOUBoS+Ujuj/pkejSQ5FZsz4rfbUjk3uL9t4gq0hf8/mEENjVHJNfIApyRMwG0S8TaAbKb6IQu/fb0nPBByJ6A5fhVPlzp09Jehzf60TdrAQqPHlhe2kCzG1w5cN7FWdQ65xOtNDArdboh1rOrp0l6k9Pkb6dXsXBgfTFOEsgjdxz02ZAKi56i3v1Hg4Hny/k=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: fuzemarket
    type: kubernetes.io/dockerconfigjson
