---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: fuzesales
spec:
  encryptedData:
    .dockerconfigjson: AgDNhNIJmZHs4fiv5QWt+FCeRzxY4+SbX7pQD1JdUD3nBjM5FncMeuRlDOu7qziW+BovdsLbV44bpyGMt5r/KPh1rayZ5O4cuiwcFgCF2+Q8DfifV4/vCcLBn+13IsJMmnxC3jPjZHZr+vJkqKo48Gn/qdNJnrG5CWrCx+m3EsMWjspO4+hVBC75TKMVo3WVRUTzFbVNtXPpLkSSaN7cDd6bMQ6Bzv/A2JLVU8YG1tRwEMH1rtgTSkbUJnNkJ4S7wp7tJw8Ts5JrbIWG73959ZR45LCnnDGFEwm55RUE63dl0Barv0sN6s1YlSa+QbaHPmeMq20/ehsxuGuWqgKMaVj37BH7Df3+ToUDSDiwGEQ1QqTzI1ApL7fNT9qKJsWcOBubw/PPaFvOsJKZsjkksQy1rnqZGzmDEgGIoBNmtALS5mXULRnNvs9wUldkiReGwahID0IPFK8HYU5haqpH5Gzr4PQ2qEUPFRga4tRPM4voX6T5FsDdR+Fx03qH/JErshjg4NGwTIzuwPafZiGE8JswlMJ+oDoAZ5jVz6e6rklWgv3e4391M4+4BF0omh0kWq19pJp+RfG7l6t1LcEo8tORBcv4ug5qI0E0heX743UdMnYR0sJ5hoP7cnMJSMgbdsRNOagLJ/sHf1QxQDIeUItO2KIC2E+PZg6pek334UMJPpsoLdcOUwCfinIromdckyV3iE2ZVZbkx5xBkbEHCoY+nBvF1K4M48llI1u2GMXFfo7BQvOP3f0Vt5wkxaRXSWuVfFbw5bFstNwbL4pPzEzDdh8+u77iIkNYnn01I9Ub3tiotTtKePyCnAxz+AFsSKIyF43Py4Kx/aBSnqJQMh0HkLg5ceOTGB17mW9IXPOs+SWCfTB4jMwbP3TeMa/5c4ifjCsMAhqkYxlggBI+VGgMiJ0xKVSoJk5RmKn0COWjEdOK5SFa3Utk/hJE++9fhYlF1XTKW5PYyrcyoLI5bf2CMR8W
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: fuzesales
    type: kubernetes.io/dockerconfigjson
