---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: fuzeexecutive
spec:
  encryptedData:
    .dockerconfigjson: AgDLwSo0RN4/2DPckaBOlNXgIizya8GTNrdaklOkhY9pNBrVnpsWilLzxuiWE9y679NWDFOT8aDgXn0uWmuBho8uG/dYGjik7unZCyX7ka8QNXCZ+U33+JA4VLfZjMeXN08Rvyi447UAsahNL8+W2EyvJ5wBp6EWE9uRpHGrOyhqlfCdvKfiwTSUxfid3Hg/1BZEqr7X3W9WySVBYswiMQfD60r9IkUONVlPMBjSLWHfr6tGzeeGoX5cXJ+IOkXvUYRuMnqIQ1Zjwp3f0dKoej+na9F764E/39xTPQRNwfx8bJDh4JrGxll/bUsU04O9mSMU58FI3YZNmgXGFJoxDMmagMcHyrGmU7Cvtu7C8tctnZ0WtMhL0cZk4rvt5UyPKYua3pw2K8MLG8socu+CwcPRkz4OLAOWEoGUTR1ZnXbhkAdVrmo26F1G5q5i8IVqw4n9U3Yvpzdiz7LOqyoqLFCe5ac8PKFtJVMtPmujdBe+3Y3va6NZO6dTItyk642ClYqqvR/TbIKacHqydrpmT6D4Ck7yUogpBzKWe2tVGtdHlZK12jaaqvOJZyUR/+sYDYAhINxMZ9uNQTpryX0MJR46yPT7OZWD781FjxY/m2fnHaKlytKlcnsJ67ivqB5Ivvbgnf1uLrd0YM1Q5c38bfiqyFNbdcT0phwP4LfoSNmZNSc1t7oKJvZHuU36FdkY4xMbZ/f9xEjlbpovrpo=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: fuzeexecutive
    type: kubernetes.io/dockerconfigjson
