---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: fuzecontact
spec:
  encryptedData:
    .dockerconfigjson: AgBklpWJqQjNF3k/J/im0jAXiRnn5ynYsIQeNEH2OgNsM8qOEJ7mKJbkR3bOGOQTTwPmRNOlnWavREGtQjhyuCcXV7gr0ceLFeEl41KRdyZ7tvVEj1QO6+GMcV1fVlWmGMnjHbCHWPVI+3NyiGdsPUdrTCPD+ft/VLdudPbdFzMi9ljJ0XLG62jsdMVxnnuDJSyAgT337JqQRvYht+GnY0dVehpZBvWIR0hLiEYjXhTQa3VaMBIc4D5ealGlodFMuicDosiJsCyGw8zYdrbhTR4pLJvOnqpPYW608ErAeayXc/8DvRo1puT8SK834puMs4qgtGy0crqtuyu9F7QJYSVLCgaZ5KXRy1CnyLxVNZaH/5zpmIY9nsJAaZRBTmbgyDeCfHo1dsQ1Vt0MvECiaGnIBRcNPN7EYoBTdw7YtMuizWg2LW6+WF9SI7evRDSazo29QVRzdcmPtyUYJhSqTmKyEB/CL4p2BrAfYhQQdQT/klZZ0ER+b6JKIcGAM2fmwscOzNdqlH/hCw8CmVB85RY+CQ+UdVqOc5EsvHkpxu7R/CFVqYhZp2oczvj+Bm5q8LsqbQhnLb5ezswFgppRf4VDh8gzHFjMWHbZAkjGk5Ol+NcmAU5/2m3//OZ/CTWO68T8mRz9vJgjbWKKuC8o5U2BCOUR0qPGowbUJdCx4beP2Y3ZKzIk8x2xyu5g3f+uEdOcrOXBoMt/RsjW3axO18+8S2bxMVaymGX/IfPXpdBEdf4CdPtOya1QHqfRKhAtGtx0CBqLVfk9encyd4rR7Ftj8uBE/fOjPeoPNaSnvkIkXZg+K/5cDlyFcfUsGU+OHF0cLDCQ/ndiGhocHq6o3GcgCwENXOySiCp5oU2TM2M77U6LLq7qwmDOKiJZB010uzd9VrIJ3zkZvNLKcMYY/EWvT8RnxK1aAPR7HxzEA/GWdfnJOEpOiJVY5oK0vy0ShDFjtXqXxJtRQIZuPQRSORaFqIGy
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: fuzecontact
    type: kubernetes.io/dockerconfigjson
