---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: fuzedeploy
spec:
  encryptedData:
    .dockerconfigjson: AgAXSCbEKLwlBO6rOsYiImCtiHUVL4XSdUoifjwQAhnkJBZ9RZA4FRONJ2dptgr+5y8dW/er8zdkzbG00MOSFBYYpC6SncfMcIsMUAWP29RyGxPQSDUxjmfmKkUzLqTlPtu496YqXZq3CO4KknJQVzWayxqj6vda9FvjqE99QOyljqoR3LQLQ7s+HEvcgVu6lCLQuP3yk6R7jO5U3sb6EGZE8CIZ39/oxcatr6MsFFixpc51zpese5rlNBRUw2yxeP6F7sQBdP1sPCsZVPHZC5WewRLVqch17ScJQCRUO3+zYEgiwX91M+c4KO+sSqe6aFCf2ZAIyzGPHRe+oi1nMjyHaa3BA7oJ0zUOuJ7dqgNC7qKsX4BAvKSg7W8lF8QxIc9br826f+hane39ojJB5WnRCx6NqwfgFp8PVAUnvio27ecGf+S+O3iN/mnCC3NS5ONpDy+zTdFnm43jotdLwDp+0A+TgknVlbvwaoNYSWNp2doPOtAn0axim+z0uUKA7iDg3C2skv/YzDjbo75eKafkwOPmZZF63Bf92XLbv3lZZv8SanGLCHvcNB+DOwrbBSmh8RBCFn9jDP9+OsVv9ociaCXAg4aKSZZigYN7bPA6TqjkO9TbmV7LDwnLGDespKwGB/e0i2csYgcMQl6Ymw38gECzVbUd7uSJxJ14XqVA2HgHQ8RMedI8ZpNzxc+8AlqpC/qrO2NXQh4RXrkIkiO28M+tNtrwrCreZvNSUWK4aKinNYxL0EH5IIHFcJREfQTMwt1+qOxFQKML7fWxrelqq1BQgV5vSW5Kgc1gbeVwkWafguiRVtPvVPbO+P3f4A1+KpXQ+xM+4XxL9RKWKq+GB7L5wWGDpzL3ZFnsYvOcOJHh84VLW7fa9Q1eRrk3rCiRFUzyz33nzdadwUS+xyg6dgJg+fBUhKH5YeJ1cp7J4zk=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull
      namespace: fuzedeploy
    type: kubernetes.io/dockerconfigjson
