---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: fuzebi
spec:
  encryptedData:
    .dockerconfigjson: AgB5M2ifi+mb9mjWM7SPRXUGEonxWKRDFfQyaongNWKt+357pmZ33dIMDNd/Qt4jynIldEqlJY4V5i0WSLHx3I79gOO0wX+oRPFKp+4PXiTMiOItk4HZx1FR2NgpfTPHnYcFmqWTWjelhHUUfMAZ2bQ5D5yEtiHgGD2vzv7zckNrfJhoxwzEJIWE4d35ADT+U3scM45jYkEJvLuhYA7usY0PpKoyr+scev5frj8ijriAO1MiTMCBg+FSU6ItHobZDCUa8qG4pprZAEwI22YDNn69yLb4E+MPVs3qO+cxP2l2aN+bfvtZ8PRvaB7mSe4aFUJPwBtlf2H3TeqHsI8q52yJz9aK4/d18D3u31qiNUapeii6x6tvhPUKeVH6F8EbQ+9ewkruGlMK1ciTzzulbZ+SCDg1T+sEcRI90SYCmVK/JwRr/ZUbQkv30FdJyOZWlOniexvxj0yRW9jtoznWL/Ee7b6BRtLI5y4VuaoI3LEj8KLO0Z4fYVOPtcnbg+FZpeRmPcz1qxZePpVezDnfVqoHSEc5y65ohdvpEJ+KvcCAgNOxS46xiXfAOyT35A0naKNGG1rzOy1Zcj8wAkRrBC9UkAtvEJ+WSJLB1DrLmzeCjIZ2pKzIauEIB6W9JbXMb8wvdobUnBTvF6b9iK3Pa+4/SMLIIzMds/yyrSSUo1QovbfbKkirTSJVFA4E9k2XL94rHUTB2G+F4DEWqUVchFttwERbwp4NH8tyRrFIdu4Gz0LeXDDfSJ9KFvNpkJW6uXOq7wP/LZMfmaGAYz+ytcpUN0A8vlRnJ0+2UMb79Tlh/XLtNHVgWrhomjC15oQ2SfQXLN+hwMYWpeDuEVXPTFai62RuMJbELw+Mb6s+sflx9jn+Xeesbld9i8vz3OndYJ4GA6pAHXrlmr/4kZG1lj5bGDcrFGOJrOiVu9y7PWC6WFU=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: fuzebi
    type: kubernetes.io/dockerconfigjson
