---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: fuzeexecutive
spec:
  encryptedData:
    .dockerconfigjson: AgCYUyQ3ZgT8EYjr2QC75gsTMPlPt3RoUrM/81dQlwHgywikOD1QoHaCRezSpagHkxBdoifrip22ns6jP/YPuh7T8gk+87RRJKXXV9ZEw6dVAaPN7iQ806wCFnfDGP2/qoUnCJdfcdd3fquY8S8bBDBCTphVbnjwYdNtEH4kM1dFdaDYSnQphmbEU7BJ6SCK0d17s6D5ZfQLLQu/R9d+WICIOzaIIhQctYmnKB1yxy9A+Dx1J+fySrcrJ9nmchZpXGlfIPOM7k3rgid1iH/o8Ka187R4Zxiv8ZZu6XGgY1FzrXmm3ne6/Qp8Mq/c/llBQ+0AkldwRJ3C6olGsJjMVSeETohGATTCfCPoYlHNf7B5RGk70nzCqoElpluRZKmZKUSL7HUkge27mMmRcUsgW8Eigbb1KDiBNrKfCORn0hI6m3YqVPTfPog1DC49tEqkqOwyOXL+FxzllJVhFpZIjjin203LAJX1aqMpTyan57PNQ/3Gja1h9ac+yzlN15SQTCzUKiWZBefpyf5/On6k/OCVTsUTZSMvCjPc+GfD3hQc7QeGzrn5s3C6egYQ0iDam+xd0RF5oYMGDqaTq9VqU9i63rG4qRf5uv3RbiN/BxONfAORqkl6kVROsbK41UqESXY7r718MF5bvcK2i9AgJwOXEKMKGLu5AkPH7ny1qj8GgeVc5EKZK8cSjdx7CDMZjFA0VzqA6lXa3vBlROU=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: fuzeexecutive
    type: kubernetes.io/dockerconfigjson
