---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: fuzemerchandize
spec:
  encryptedData:
    .dockerconfigjson: AgDEMXUKL/lfj4K0AXT0zzwPoCk1NlMJlTA0PdC53NxxK14F6DCBGpfuhy+nhHBklyiwj9SXuwH+LEIcu0+7DypwkIj297UZQ77uwYmL5K/YtRsWeMxPq4WLSfheebxDq5fxNQ6TyecM1rx+Mb6VkN2+a86cC+FTYAaelcB4Fbnvkux9BP/bUUqn75FZrSnOqPaOy43ofR42Jg2YXy0huRviWS48qqq++e1BmXOMf3hx90TUArKN56fvGeS/tiwcSD2+d/5wRKYf3G/MVNobE1el+sXISIpKjifvoAiIc4wiAmLERRa82/xWkQHARDGoxvRzYGQ9Czq9+u3pVNWegqk/Q9GBN+phAgj+2HEGsYqsGqA2ewCEmu+UcXs9s71zVEI52YbOb9QNqlQSwpmrEhvgO6+7TntjP7Gz1CCTKxZ0j+BnWkm9Fv+LYclksEWXY/8DBp9uz0ipPCNmMwXwfXoS5zPjOra63n2L7ZlbFIhG30Jmle5HyzTsvvVU6BcgwacJzKk+osT4azB+Nrpe4wnl9qGbnu0sOm6pPvS2FqDc8LiC80OjKDrVKGRt5xZXtYcrfaEXpKIC8HCPF/pXy4MIpHNXLTULoOkNphVPyVIGgYOMymahpWtEry/9s2DZPmNh7LJV8lvBy8R+4R8j1oWDQqFwwjPzQvgGjIUDQFodc8zfRMIsOCfTqjjMjGYZ5u3NByWQuesAswbyMIVXB5m6WlTBw0HHviFrTES5tCoRbeEfkQXlK9q6pWUeYf39h6i7jqZegO950h0J2Oat4yHrZJnFkF4mfGltSY05gmVrA+UXbmEXi5D0hvl+ED6nojoQd2nd5v3NvQqR0k4pKmkW3S1Bb//V01YPCfUdWYSo/vLBTmIoB1AIHnJ0Bqn4mqyQuYw5uihu4StGufrN9C7q9H/ef25vZcP/GS5/iydFcd8=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: fuzemerchandize
    type: kubernetes.io/dockerconfigjson
