---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: fuzeexecutive
spec:
  encryptedData:
    .dockerconfigjson: AgCoaRRPdYLsP3X/mNVxTa8tqZdRnaSLuRulDWEzGnkIlNPNcEcpkHUiIjF+vRwk6ncKUadmTjy5UqeZ/wjRMOk7GljjOvG8UgILo591drHPxOTBMIb5bjM4jDSmutFcazYYZkMvFGvybFiflYrOoXzgZiEeO6LH9Tgg4hzL6iM7Ema49Cn/gfXmOX427jyJrdYg1+MZxvhGbyvRF5o7nT5WRCC6M11T5XX4cknti72kYiH9ICYF+zRC7ZWpjmZvJtKsO6fNMLdAvyXHEwi67zyx3Ja1ZikxoNYOU3fj1A+QkQ4iHFGq04AWjWCm9VK2PKAdARXWhwR7YEzdsEGovQPchf8qa4Q+bsxqv+8dxaleyWPlZ3eAUHHgzAnje6xSQVbdIZX7T16zunerrAv6CHdREetJp4pE7TZga3DpKXTfSauUz4oXBfqEWopz9hYpw23G7ORA1fES9uXxEdNcG66u54hHWhtPlv78C7MHSSW1rz4a9rJ2HZJqyK2nyNGTJmaCb0woJXgEMdyjwy9gzwokzfwdeCg1SvEhek8QxFG2MICvR1ZPQRdgRFm/dvg94iPIAIvcr//9jKxEKX+F609JmVUHFgwrSqWmsDD44lQiMgtWEgtEIpzEwfx9fCE5DnSweqwBugig6E6GFdrEjz4BPxuSXyvs1tHRFUc2IqSot2YTBstuS7Q0D1UACVh4H9uf/99eHFeIwaJhDvntvWEoLLyKgRjaOphNRklDNhIZ6c8PV+Ci1BseOtPU1Imirpb+TRPY353TCFrIiDv8TAjwyAGRQjfXm05KQ8EUnkUBxDilRyJPJwxKyVVDJObgf0JmUB55nxp2gLwpWAJDR70qWsDCuN63sKV+FANxT1k89xHp40odpgMZ8CkHTHCvUKZ5CA2uAamN+Jo06rNz49IQNLORhXt/qftr/O6dCNW2sds=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: fuzeexecutive
    type: kubernetes.io/dockerconfigjson
