---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: fuzeplan
spec:
  encryptedData:
    .dockerconfigjson: AgCRCaSJtM+hQZgcyIXuQtOyFsNR+46d11sLOIv8hbMKZoUnb3J85zgmLDOkvUhJSS7kQXWO8xTq1EZ91aLyCTsXwCOjhg8+I0PfgzlSFIYBr2HGO9s1TcdIZcbWWxSr23tfCOfXHB/yOU/r3AyfQvubf8Y7ryunr5RYmi05pvCIHAo5lhYmOD1KguHSdZcG/XrpEYL/kU021KkY5GMJ6QN6jsBp+dp72kDyoPzSWlDGnCqzjSjtogV9C+XEKBoWT9rg5y/t6QPun7OEL3tunf9y/OzSxoNpq5M0+iT/DG2HVhquTOvFCe/bp+aksD7JlNp7Jx/vizabotYW98bctT0rvqBED8t84/6Valh7vG0ronTsISQj6M7344r+CLh7YULI9Dk8RM2WdMYmHrUAic2FdQWEnO5u+B+01JrIwsDPW82BQBnz1PgeZfAvqeTRUrzqWQiT1bry1Yxoc4VGvC81k0NHO1uakv8eZD32ehDRDnXj2ZbZMmgwNHQeW5Yg3mIfKA59GHpee+ZvG5YTGHhydIElIGoNeE6tHn4yWMc5rx1Yt9bs5H6XJDgpGVZScSSxU8ISaomtkjiFsIICbavJjQgZN2NUkRH3q3lv7ZpCwgM7plVbluZOEK7ZLekIr2rirzZnQ8Id69ZVEBTsr7sUeK06pdkytNxoNf0uZCq1zOf1760v8zPRxR4oMs8zaGUxYgB4jOtYCPGuB8bwAq8GUmw2koYIskJkFofJMRcHZpMP0/fiQ75PWNrzOUNg4BxmOA7fEVNg3P7CfPs69SaTe5ZlNjOb75k9gO0zncDkpqYTBmwJWAz+uXd2KUYMu2kK/VwuOTZ3aLfuRKjvOmsHoFVXjhxkn7roTwzn24Y4YTTstnU4B1qLNjs5Zu5emjw2KlKA/KO6aSlpjrvYwaulZNhN9AQ6K3z54YNLbYUOnYY=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull
      namespace: fuzeplan
      # The Secret pre-dates this SealedSecret. Persist the adoption marker so
      # the controller takes ownership on its next reconciliation.
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: kubernetes.io/dockerconfigjson
