---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: fuzeservice
spec:
  encryptedData:
    .dockerconfigjson: AgAZn5T9YoUGQO7CEVP/a0eN94WVCA0LOIaRbIDBqjZZeAuvcKmPOqLQS99VljXkjfCND2ORcaJlh2KN6q1yviX5WZLhYCyrEP0/6ENK4+q7L94Is5tY3w6KrvByhK45wG9+p45aPR9SdRNmk9KlHQkcHxN0dgoabYMdGD6ebdShK4d15kVT31JNLwY1RKGh4KvOFQUQlN6VbeSIkdCFYLJMjcPzsLo4ykh6duJuA8CiRNU4lLoiQg3K1Be8MJKOvu5ONiO/3Tzg4AL8GAi9WSYl7b/sNoAh02Hh6daMnOGp1+6bokJBEGPO0oEkgvVqLBN0U3I49poIn3pJW194vjm7BZ8ceKw3RfmN1s6W8NrDulmWYIFAEXfP4wqAPVRdwqR75ZeyJbdaRJd3DjHkLGpG2oPC9xPjl84ZA55ljXB7ykvL/IhLGqDzxKMCO+/ZHMu55gf85DMvtuL5iPijHM2aINDo0yqGM8ggMMFsjb8UPbLk8IpoQQXuRgLSSSbdz82WEQk834eMKaXqKzY0rXJEqT9lq8IXb70oietbrAWrZbmrvXHZjdgKa+U4bp5Y6sdv+JRkU0BgSHMKNAKZZhlC6egBb3fWIx2PbskR14stq7+0znRbiFtwwq+voLff8cYLL68Juin2eWpTEICZWpKDnWx3e841mkIW1runyY6m84XzRa7EhN1z+ChG+wxc5xR4tlXyV3p/IXSNu6VxXsqcm+gGKwfCBWzVNsq8+EIHNnd0gwPc0U6HZePXlQBiQXtWmDw+NFYuCZCipLyfIF/EQXLJtsMW3jvVdaXB8O5YUqHZG4rX3dTq3dnd1c0q+Gwf7f0GN1kO/TH7HxEsywioGS3U8BoKisUGND5dxLLLH/zFlCBzvd3sNZFi9txAJPnhJFaB/rrhlwijnwrYbIgW7fOuLzFGIKYk0BNMZXNdi0o6ok/ShIQZ+reSGKayozl4i49JJCycMsVxLB11ADcX7V4m
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: fuzeservice
    type: kubernetes.io/dockerconfigjson
