"""Executable invariants for the consumer-host-collision guard.

`terraform/contabo/materialized/consumers.tfvars` is GENERATED by the
`cf-hosts-materialize.yml` auto-PR flow from a consumer repo's own
`deploy/cf/hosts.yaml`. Every label in it gets a Cloudflare Access app with
`decision = "bypass"` / `everyone = true` (terraform/contabo/cloudflare.tf
~line 356) — publicly reachable, no Access/auth gate — and the tunnel's
catch-all ingress rule (cloudflare.tf:102-110) plus the `*.prod.fuzefront.com`
wildcard CNAME mean any Ingress in the cluster is internet-reachable the
moment it exists. If a consumer auto-PR ever landed a label that collides
with an infra-owned hostname, merge would publish an infra service —
potentially a raw datastore like Elasticsearch or Neo4j — to the internet
with zero auth in front of it. That rule previously existed only as a
COMMENT in consumers.tfvars's own header; scripts-tools/check_consumer_host_
collisions.py makes it an executable CI gate, and this suite pins its
behaviour.

Match the house pattern of tests/test_cluster_query_guard.py: EXECUTE the
real guard (by importing the actual module, since the guard here is Python
rather than the bash step cluster-query.yml uses) rather than re-deriving
its logic — a guard asserted by re-implementing the check in the test passes
happily even when the real one is broken.

The negative cases are the point: a guard that has never failed is not a
guard, so this suite asserts REJECTION explicitly (collision with a
`$routes` key, collision with a `neo4j*` host, and a wildcard label) and
does not stop at the happy path.

Offline: parses known, comment-documented file shapes with regex. No
cluster, no network, no `helm template`, no `terraform plan`.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parents[1]
SCRIPT = ROOT / "scripts-tools" / "check_consumer_host_collisions.py"
CONSUMERS_TFVARS = ROOT / "terraform" / "contabo" / "materialized" / "consumers.tfvars"
INGRESS_YAML = ROOT / "helm" / "fuzeinfra" / "templates" / "ingress.yaml"
NEO4J_INGRESS_YAML = ROOT / "helm" / "fuzeinfra" / "templates" / "neo4j-ingress.yaml"
CLOUDFLARE_TF = ROOT / "terraform" / "contabo" / "cloudflare.tf"


def _load_module():
    # scripts-tools is not an importable package name (hyphen), so load by path
    # — same technique as tests/test_deployment_watchdog.py.
    spec = importlib.util.spec_from_file_location("check_consumer_host_collisions", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


guard = _load_module()


def _write_tfvars(tmp_path: Path, labels: dict[str, str]) -> Path:
    path = tmp_path / "consumers.tfvars"
    lines = ["public_app_hosts = {"]
    for label, repo in labels.items():
        lines.append(f'  "{label}" = "{repo}"')
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


# --- source-derivation sanity -----------------------------------------------
# These pin the derivation against the REAL, checked-in source files so the
# guard is proven to read live policy, not a copy that can drift from it.

def test_infra_owned_hosts_are_derived_from_real_sources():
    owned = guard.derive_infra_owned_hosts(INGRESS_YAML, NEO4J_INGRESS_YAML, CLOUDFLARE_TF)
    # From ingress.yaml $routes.
    assert "elasticsearch" in owned
    assert "grafana" in owned
    assert "chromadb" in owned
    # From neo4j-ingress.yaml.
    assert "neo4j" in owned
    assert "neo4j-bolt" in owned
    # From cloudflare.tf launcher_services (routed by a DIFFERENT chart's
    # Ingress, but still a platform-owned name on the same apex).
    assert "litellm" in owned
    assert "argocd" in owned


def test_derivation_fails_loudly_if_the_routes_dict_moves():
    """A parser that silently returns {} on a moved/renamed source is worse
    than no guard at all — it would report every future PR clean forever."""
    with pytest.raises(ValueError):
        guard.extract_ingress_routes_keys(ROOT / "does" / "not" / "exist.yaml")


# --- negative cases: this is the point --------------------------------------

def test_collision_with_routes_key_is_rejected(tmp_path):
    path = _write_tfvars(tmp_path, {"elasticsearch": "izzywdev/EvilApp"})
    violations = guard.check(
        consumers_path=path,
        ingress_path=INGRESS_YAML,
        neo4j_path=NEO4J_INGRESS_YAML,
        cloudflare_tf_path=CLOUDFLARE_TF,
    )
    assert violations, "a label identical to an infra $routes key must be REJECTED"
    assert any("elasticsearch" in v and "COLLISION" in v for v in violations), violations


def test_collision_with_neo4j_host_is_rejected(tmp_path):
    path = _write_tfvars(tmp_path, {"neo4j-bolt": "izzywdev/EvilApp"})
    violations = guard.check(
        consumers_path=path,
        ingress_path=INGRESS_YAML,
        neo4j_path=NEO4J_INGRESS_YAML,
        cloudflare_tf_path=CLOUDFLARE_TF,
    )
    assert violations, "a label identical to a neo4j* host must be REJECTED"
    assert any("neo4j-bolt" in v and "COLLISION" in v for v in violations), violations


def test_wildcard_label_is_rejected(tmp_path):
    path = _write_tfvars(tmp_path, {"*": "izzywdev/EvilApp"})
    violations = guard.check(
        consumers_path=path,
        ingress_path=INGRESS_YAML,
        neo4j_path=NEO4J_INGRESS_YAML,
        cloudflare_tf_path=CLOUDFLARE_TF,
    )
    assert violations, "a wildcard label must be REJECTED"
    assert any("wildcard" in v.lower() for v in violations), violations


def test_dotted_label_matching_only_a_first_segment_is_not_a_false_collision(tmp_path):
    """`elasticsearch.foo` must NOT collide with infra-owned `elasticsearch` —
    the FQDN `elasticsearch.foo.prod.fuzefront.com` is a distinct hostname
    from `elasticsearch.prod.fuzefront.com`, not the same record. Only an
    EXACT full-label match is a real collision (see module docstring)."""
    path = _write_tfvars(tmp_path, {"elasticsearch.foo": "izzywdev/SomeApp"})
    violations = guard.check(
        consumers_path=path,
        ingress_path=INGRESS_YAML,
        neo4j_path=NEO4J_INGRESS_YAML,
        cloudflare_tf_path=CLOUDFLARE_TF,
    )
    assert violations == [], violations


# --- positive cases: no false positives -------------------------------------

def test_current_real_consumers_tfvars_passes():
    """No false positive on today's good input — the file that actually
    ships in this repo right now must be clean."""
    violations = guard.check(
        consumers_path=CONSUMERS_TFVARS,
        ingress_path=INGRESS_YAML,
        neo4j_path=NEO4J_INGRESS_YAML,
        cloudflare_tf_path=CLOUDFLARE_TF,
    )
    assert violations == [], violations


def test_plausible_new_clean_consumer_label_passes(tmp_path):
    path = _write_tfvars(tmp_path, {"api.fuzecontact": "izzywdev/FuzeContact"})
    violations = guard.check(
        consumers_path=path,
        ingress_path=INGRESS_YAML,
        neo4j_path=NEO4J_INGRESS_YAML,
        cloudflare_tf_path=CLOUDFLARE_TF,
    )
    assert violations == [], violations


def test_cli_exits_nonzero_and_names_the_label(tmp_path):
    """End-to-end: invoke main() via the real CLI argument parsing path."""
    path = _write_tfvars(tmp_path, {"grafana": "izzywdev/EvilApp"})
    old_argv = sys.argv
    try:
        sys.argv = [
            "check_consumer_host_collisions.py",
            "--consumers-tfvars", str(path),
            "--ingress-yaml", str(INGRESS_YAML),
            "--neo4j-ingress-yaml", str(NEO4J_INGRESS_YAML),
            "--cloudflare-tf", str(CLOUDFLARE_TF),
        ]
        rc = guard.main()
    finally:
        sys.argv = old_argv
    assert rc == 1


def test_cli_exits_zero_on_real_consumers_tfvars():
    old_argv = sys.argv
    try:
        sys.argv = ["check_consumer_host_collisions.py"]
        rc = guard.main()
    finally:
        sys.argv = old_argv
    assert rc == 0
