---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: a2a-gateway-secret
  namespace: fuzeinfra
spec:
  encryptedData:
    .credentials.json: AgA2Ndm+0tW6vcL36dVVFk4EIj/JbTRXZU0LKETsQkAuG4uGuqCLBWY+cPNNMPH1FZQOKSukw5duWbP+4CszMK2W4GlVswmxrn6za1vCWzLGlje8DpSMrPNUMBs8AMPNdzhyGCuVsk+YPeT6U3PPzSEd1fFpi/HoMbbwXXXFpms8b1Wn2FBwRiNkdXUS6gEF9NdFE5xBgotSB7n+x42RVRDn3Cs6IwZtBqHYVGeh/Kqe/nC6qwj7b1C/qP7fjPhXsZ/l6vW4Zucfc5gadVDwRUUhD0Y32seBmRxSr0dVPdFfHowdxVHKmbSrTTJE2Co21Cas/XaKOdS5zRgqrlz1w9LKe68EZ1vkIIjl5T+5zB4TcBcMkcpcunl/9lCmJFjt3JsoKcySMPw49UvtFZ2VJDOd1iWoG1lbetBX9vMt9D75nmerbAXDsfg24cr1qkM9yas4I8e9EKHlVWdrNnXUsCuwJJzTN1GqCQ47StaRTBf4d4IcuJnIjuGld9z4/V40LhNA8/LBt6KB2DZ3DdU5T28nhNq9namUxfgpNdNcD5SwRxNZm5v7XOk/dTZ8SpS4po3DUpsGLWPHIGY4n7/xyhISPoPAJ9XT29zkRYfA+fcwvl9pDp+2EMbDKdUg4JbJIbbMkYL6iW1FQdXbEKd/hIl3Mwpz6vYh9LLVCGJOILSXv55whgeU/9CQQi5q3aDY+S2SQzICTnp3tPpiD9g3mGgeFwa6C+C4h4K4ytmviROoUMo6AjXoajI0rDBd04+yyNRRihPJJNlU1EO50/gNxA5Z6+nAAdmDoEhAPXPSuYTqX53iVsUX6pOXiKHkQY/bAW5WbcFrwAah8+SvTKGpPZ8sInd6nkYqouPOQxtjvAjZZwKIZ3eyobPRzttK5DjrQNG7tO588iX4Wbpd/dORplLG3fKghf70AJGWizfNZumcOrlf93s+IK6hWdxwTaiY3Z5BwtDVwGBiH4Zm3WiBlF17H2yGxPBoD2w5Z5vLPx101fJNb6NuV/abY9t0EKYaLnklZo26dci1ng7XUqPKDpcOIKliEvPGxpKsuqSftMKCYPFVumdhIXzj9ZCpi/suWCMkMgkt9ta20WxTd2yZqU6f6wL0kZnt+G7ScggAaaaBeIHAlQOunbG2VJ6CPMWunSNT7Yglr8nYi4qpOvu3ts8CsM2CkC7T+7piFHJG7YYc/lVLmZvsDUDXC1B8Df2wVWjm8rppQdzz3TBpEnpmObvmEvh+5myZOy0x1yNb/b5I8uidDCCyHvekg92R0CfX+pFGKNdPnzd1MVNDJerU2STX9wXvwNzQ2bmHB7B5duRJjR9OBQbr1zBsgoi8yn+iICGddfmRxguwVYoAhn2VEfCfM0BE/3Pw8TZ6FCCyToEnqljEKUrkSPt9Fl2m0KZ4hw==
  template:
    metadata:
      name: a2a-gateway-secret
      namespace: fuzeinfra
    type: Opaque
