---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fuzeinfra-backups-s3
  namespace: fuzeinfra
spec:
  encryptedData:
    BACKUP_S3_ACCESS_KEY_ID: AgAitYXJyXmdTpTiXSpx+otkTWfOKjhKxvzoukJnzecfLji5rb51SMF245t47LJd67tn5HIPBb6DgJYdf7xqwWyF2fxR2YiWNoUy8/C1i78qMj+XQDAAtx/gsI3eyGEA3JETUKSx4G6p3VdX2Nqaj59bugsavqAdoe+HSNKuX+YVT/h0yLr+Aogu1WFxuGP4VVtvcJjeb8SRZ/dssklRR7zqMkzwVJupYxrvzd59IxWHfOSoj8ixlEXCb/rxNf2FLBr3fvv2rWjkZCYvIyv2BpsANDnq5CTB5aPcZt23q+t+HKMJKJgndJChZBGQiO67K/La6d+GqKkuNKSFagodPCZ5wXtrY/dJndK10Kjkfkal5vAB/NrPcjk+/8GnvKbn5Zgxq+yL4XoB6/P1T7ijPhdvyOFs+jnu+b6h/MjhAnZwDWTYT4pdMJzDFSA3wEpAw9pzWliod32yU9xxvYRrqpCkG6MFwnHIls1Iks2/mrr9wQvr5jmFijdMwC56lvewffcJqzxV3pFRjNUIl8BbhmWeuQKxMx/pFolg4ZpxaFTz7wxjfE7A+XBFx8mc/jIVoeyvVx6WMJr1hptfOWm8DYQKZ2TI3u3/tSrcFS+HCiI1j/cnYFAq4J8tYGGr1Hl0NZv4Us5Slx65FHctOOw8B4sykYKE4kCWEstYSsnzFrSJ97pnuZiZQPX4bFSFg71cK+bDEWyEZFOZmsX+XieGl+UEbIVQKGBiNsRSHEYQcsLViQ==
    BACKUP_S3_SECRET_ACCESS_KEY: AgC3L8DPRQg+FC3kQEbyPslq1icUr9e0Pr1WJ4heYjM6MJNBvOoREzb56R9yBfKzqKYCLpob2Eq3tvGT9U6LgwD1tObKyIjc4CV1rNl/D6stsCVcoJ3fCFdHE4Pd3hGu7bAEUZ9DUPZl0scscajAfI3JFS5ihEyy+HjYD84f6KQHARRADV5hOb/MDMPQVa3LWNPUgMn3A0cXkSH8hPFslS7ufQ6r9uFu+aYMt46XwDXW6+1eOXkat4LW5ytI/5tmUl84IpZC78+DbNeF0TIkNydcgwVh1L7zYG/VHa3Y5auZ3+wALsmbGsriwkmyIQ/MzoYHar0eZIlN21RSs023HLNnyXSgSgXjx5KVM3jtR6UeOi+rb8mHbYD3gstPUVEW6mUYoWsA+DpEv8mn1x1awh28ATBE+/86R6zdXzPW5wAzQ6GbbRMplwqkeFka5acnbWx+5nCc1xeo2HfRDvq53eOamGZKXDXPf1VdyG8QynURYvTzi1flQyGUmnJAlH2bAgaTh9Cy3IK9YTleJv+HcHlC3Xs3M9jsyK8btDVj9Rpn1Xs+9mVNvqjVRHO0aK9nh7wY0Z5BG/VD0TQXUxxFg8ttJANZvR+juquDRCEpw76IlbrCACPAe83dYG+DxX7Omud1L1h5qyv4xzo9nJgPQNfLO8/5Zp7Wf/GnBiC04hcIjSdR6GDma45YfDKuZ4mtAxRyXRtcJSOp232W6ywVLuQJ73OjI3m/kbCUP6Lk/vxIYg==
  template:
    metadata:
      name: fuzeinfra-backups-s3
      namespace: fuzeinfra
    type: Opaque
