---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chromadb-admin-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    token: AgBb5/+2FIKSFTUiI6CMk3ctrPAZMTfdKssl/VCBpemwgb/TsQZj/W9V+yNiuBsyVjiuC6JU0GP5/eYLuUf10tzfxsXrGBPo3nU3mDar5oMBhV6HxhJ/9IuaYMdsmsEKYWe0WsMNauRYvrHpGLRZoMloMz8zQPZy9ccxNsFtzrEDtR3CwnG6eTHvd4bTqwotkCebBCejHeEsGepc9rRMGQguGWwlqCxqsEt6GYDOYwkoiaOsqJHEbav9n46X2yJJrxxQQbf848g3uZZ/lmxm9Qt5sIg3DTtPeXSddTyqCSKu5TWAMNIWbERUo3Ftkp0DYv9tqQIrLUhMAMoACh+NZX09c7/ecDzFOJjWFnIqbKj42LWSak6dQOTJ8NveH4rbaznUXc0OTLMdLLCXzIpVZH/aWIQbvjemzEZ3JzGBXHM1zQYBjp25/vFv6LxXd1g70hZJbiSwBA4lKVEBbLDov4jv07HRexpcSW2elMdtQnRD4g6I5l58zeUAP7r7pdDlkBZqi+sE7fQX/8A3JQsv4QZXf+Bhqjo8v2O279kb9boxvOj0/bE8ghhQKBj+ssuvdBj5QRaNkzCRXtnDdEpwvnNIafBxOP+0lLwCVMI9hM2uaQjK6SZUvhK1zt30tuXxBSnrcWx1vRHiien3L1MYblpIX7D8tJCXurwHwtd5XRIWQYAIMkUSdBKqTOsGz28X6iazGqM3UpMVfoOqAkU4iKho/Rnde+boaop/ey8o6LCMX0okX2r5/wkwvVYMRTMGF6BX2YSM0MeIF2lVaeqPYczw1A==
  template:
    metadata:
      creationTimestamp: null
      name: chromadb-admin-credentials
      namespace: fuzeinfra
    type: Opaque
