---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fuzequality-chroma-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    token: AgDIV1gE4GV745wXxch+4Wn6LLOZSZKSagxIH3h4xcvndpuehjhEnWu9aLzuVi/CxcJt8rbvtCp6tFWij7Sk0SbaBMeKhVKV88hd6wiEgvfOrXAb5aXo70Uwhg1Lt5FaSSpCA/Dta5J9+4Nl/9Aom5XJGNYC4ILv/2ORfGQpDm7OcPzssKfl0B6PlG3jA0kLEKvXGQ1sEzbr2xS7KResYtDm777iL0woZP8Bm83qeEwjhOPrPgY9nYFa8e7zeFNOHwd61CpuDFxYbX7qupKis2thDRC+0xnLwwKnxI33mZm12I1FD/Ev8eWjnM7YZByCNjfmBNA5coJiChS0/nH1cnQpH7XnTPddovQZqcXG9q6Pww0UFZGXIU7oOtPv5HYaA7bj4VKkLhNCyAhJRzrncZp4jzEbKu5LrLLvofLzFhS86AYbibOQ48TdBv0O13Nf5AGzIlFFYK6GWUfPwN5KTxPu7D/QT/SPKjQst7OnKnSSOhoXCcQXlM/5ZxlJ7IASehSyTLZe64vMEpSWda1biQ/PrOub+6qt7I40rkJtqeas3e5EbGm8R/F3u27lnkAr7G+2OtPe3R+8z/MQPu+6Fyn35XneKNSfjAVXXlQs+zjF7Y7gjTZhVnF7gIoKVvSMfwdvbay/5I0GFcFslhWCALFQvjYS7c5ZL85ubC/37JfKH2oHianD9rHBdQpOm/ONAkgfhRV9P5GMXDt7o8PoVYaSReCG9zn+nFmd4Iqu+34w+a5H5S4k+7kfRdEyPXkiObSFmkWlWIcGx9MSYSOF1xdfTg==
  template:
    metadata:
      creationTimestamp: null
      name: fuzequality-chroma-credentials
      namespace: fuzeinfra
    type: Opaque
