---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fuzeplan-repo-digester-chroma-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    token: AgBrAL2yhBkLGNEZbkXlkLaSXlSI1TkM78IREiMtw4jK7I6DlKStf0lfbzB2nF3TeUP04KVNw/fIJVqB89e11fl99f0L+TT655+vHR4/azTvkKpBrlLunE/IfxmXUvbp16G0ZkJr5A8MKNxhhzImTWC364vATgvp4IzTIN/RWwGu9j7msmx1w5l9hMHO9Bbja6tnW1O0TaviHu/CFXYTowZ+Li3ieOfuYtDpF6g0FisDPfrGkESDIgKhD1fy+k7z9afY6duJ+sAnSQVY/Nn5vbLlfxdy0LXXRfF9xVoVcIV8rwRboXne9qY/Klk4TrIQ/4ywpVHpWLJzEztW5sA5fkD7kYEcwNFFUFHYnWfPz2CZC2lu5+DHlBaWFHC4PA/rpVXoARxrzOj0p76/VAl6Kyu3gBiIQJJf6RSOjJooLxiUsYjcWT5ZUX6hZStxxCHFRl4+sdw9SaIrIfCBw17s3QI9IrTloKeKpe7sKiXJLRb9LxZkmiaYxxis30d4yzoVk1OCzEh0pi9CnuHXZHsliXQ9iH8njWSu/0uotQNTGBo0Bq+8IKZG1bmXsdGEzOmlKkFN6lJqHknH0K4u1K8+XEn3jeiw222uU2q/q7f///dfsudaDi/SZ2M+9ywOitatIhosK/XJNDOJHnQ7mB2iXpBV7d2GVkaTg6fxwivT+NyVbkiGmn0ZEC8S6SPIhaoNyN2tV0FHS/pG0U2JZX/yMY0E3k30W/B12Jq35Y6ZeO3iXVvmXGVXeR27puA+fPMqM9SNOkNM3g1iY7msd4uckPLixg==
  template:
    metadata:
      creationTimestamp: null
      name: fuzeplan-repo-digester-chroma-credentials
      namespace: fuzeinfra
    type: Opaque
