---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fuzequality-chroma-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    token: AgBvi6MJOO3Mi4HZWm3mzz2aGROVGxOVLW+fECEtmbYSu1DcKLtEiimRHaPDNdUaymHj5DVHaQ4/pU6Da+fpUuooiqanv1aK7wPr109tsP2iOc//qGYOaKOG9Xe+Q89depGA6dgtM3nvqfkAxcJtoXPNRBJ6AsGHSo8euiTvSFQumkXyZPWLKNikVQwQm0y/ArBGgvtBhrYSejRKITcWtkEYKT+221FWPpVJDS1vbu/CBs5ZT29nCWsmRPP+Gu5sNDRbGk6ZXeqKbfsorrJK0L3I9f7qS5Pk2Ib80lgM1/wB/SGDyDXKojGeFo8nQu81XR401gGIU1NZAsRd7yW+Tv/hdKtVFqaVPOyEvUBqxm/HRtno67MEnrNaamqnO5ay7GA7AVn426KDIUKEHj8+tBIC4e2FOsGf+5y+IAKC2vyICn67wYIcnTLXeysnAH/R3XYJiGZWINO8eilLA5Ou6hBxXz7ZGNrFhIsqOl0UYomnWGzA/NMZcjwxK7O9MbjUotMGCzY7CH0v8KTfy4IawsQBq9sKShd6paHsogbGOI6yB/6Q3HzZuhpGlIb+JjN1+Gc+D8+rzmBqsJ+i4V+n1xqeaX1sD25KO1kw25beW9bJEUy21eDTv6A+uJ6XaER5CiYG31ol5IXu3+eWTd7ISv5hOSe7bOV5adTlD95Y9hn9CDuT3fNJTI5gWmzn4ClCt8Umoboz6hYHm7UmBTseQlmGnBbnHe34pVKJni5s+6qgf2m0b5nZBQzwQTUiwN6gmeJM4aCPJWx9QFsk+s5phvh+
  template:
    metadata:
      creationTimestamp: null
      name: fuzequality-chroma-credentials
      namespace: fuzeinfra
    type: Opaque
