---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fuzesocial-db-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    password: AgBhMlfk9/lC/q9Dc6e0B59nGQ3HLP0mAKxVp9q4GN4dq/NMLMAMrwQpo/2SDsOHcnkOK167soEltBCRYSc0BL8A2ADdnnQRqs6N6fDvw/8b4pwkf/CVrIqLybFhW5GDRh96Zh6CoUx97RqkyTqD9lj0ztR2BRzEAeFmuLcmHA1muUgio7r19Y/CK+sXjmeHnk5WgZ7XkRpOMbQtGvsJf/ER+zzJzT7CTLTV7UxxWQLHwal90eIZ9K+H920d93KrTsbiijaH/9RtKTz4yySs6eKPkYA6kh2E9yJUxF5OStPiTRRRv/1frTQeDK83lt+0W1nTz5y9QaHxhGKvhTdo8Q7AQKnGGnWusbi2QHHL2KlMLiFHet6l/SDqNtTv1xPwn5P1yp0GKNUa0h+wFArFgnqyGY01UGy+Wt0PTb2DE6RXSiG6AVodLVHiUzEHOYIrsXwCPIWkOz11yhwd9elMO8ai4NW+yKIyy5zIo1JTolQtrKe0N7mONYoBHooc7sDLyOvYlnd8MN+y4nsHZdhRfBxrdecpU1l3aT2pBJakTZQtmzSQ7PpxCbxAApSTHn/3n5d+omJd97d7LJOIiyBhx9YZIRzCl8VYHg9LGibPhclC+KJxnDXdFy1Eus63YXp2N6mwQI7BAowLOi5V7CBhZdmIO/Y7J7p/73enbUjLEopz1J/Rv8FkxvPyvi1wJzGuuoxkFj8oThigr+gIX/Gz8Rt+AVdF3ERumz9bBzMwF5LN34z9oPpj1k14hiHlTLUjHuM=
  template:
    metadata:
      creationTimestamp: null
      name: fuzesocial-db-credentials
      namespace: fuzeinfra
    type: Opaque
