---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fuzepicker-db-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    password: AgDQQQ6mAkRcsKIz4diEAKyzaXYOCdudehXGxYxq0XLmUq+jDGWNFw/uvDZhk2bUUWbyg/4dwVDTRAdMcxuhY8A2xvSqY3nFH5hKdGNg4urdFqfg96D5JOKR+6NL0Aj/2cH1J0cDr+6WMNWbCCvG9Lgke4Z+aTqlM7RfaqVnNtN6cvOIvLUzVfecdwcOguF6bOETTVdahkPFRQKhFpUZPt1pb7R+IAmZYSDrbhhVTF8YsE5kMZKJCJ7WwO0FQP+4z38YBWILvvrd+gyeaHlmbpchv3p1XPIDkb3kei2zwA6u3MkJq3VdhIyKj/ziCcu42YHrqGEx0F14EPoLJuM9y7qO+JBKVwtDJzXC3i7vwUrNarQe+H70dMjqseNlEkxLwZVJdYx4HGASYToIrioPCEuyAO0jlXtgA/vuP/mQHouqRTlPdCKf6F51a+SbwksoZZ9juvq1HrCx+/PJ9SAE1ffVqI3B5ZhuiXUPumVUBn9eEbEO/GPHmN8eJwAEhAM6lV1mVzoNfit22sS6XgXXbSChRAuJQ4PKUjGqBV0JGjamh3iEKYaa2SWokSirEqM2y/KMLNoH4DkR6inTou/QPVSyIwXokO+jsBvtwmjm9tBCtw8DRDcJi3CzOJx/S6QwfSekLqzM2cTJ13zn7LIiioS+GYknBsF6mnfJoW+sikJhprUANaZ5Y8L08lGLMO6EenV/vtwetkEnSGRtakxCZDtfJGJGuJ3DHYHnRi6eprAI2do1w6y8LUCeRRKB5ODbb8U=
  template:
    metadata:
      creationTimestamp: null
      name: fuzepicker-db-credentials
      namespace: fuzeinfra
