---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fuzecontact-db-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    password: AgAtiVcgyfrWU3ww0iI/D8Xy617VK78x21zgknUApM3mvH4LDPaaThmCsbOn1+imjEvifeGCuhuJ9JFJq4Ydw5t5ONUFVm6bSomg4aOd/25rZMUqZba+5MJzTLY9V8VgODYhlsKiBZ1/M1aG1MWqEWEE1ELdKehl+Z+fXkATUWZatIudbIsT5P98WlW03KF1VJdMLYTLpiMTUgPZbX+DG9QB3VvGHOq8BjjfMeopexpceUD4OlwaceZH9kuuz8IxQgvInB0YyRGiBxVIybP6LItpsAn1WIQHYQphqktCK0R8WVGSzxQD52JfX7EAjJTzS35XBNNH8hHbXC8pRZIawd1BK87O+5TDdK+ZJeVm1nCPxhvG5beicbdlL/05Pz/y2VhWYezbaYsZEm1zdGdgtoKICmcdGKZlMoQY/WjLLvBFsz2LYQvV1OmZLqb9ybT8tJ0PkR8CP61aLukvoJ0ACdyyUga7cWPuEf1PJjllxt2EkfoNSqCXzpOKbGP8o0+Fyat9HAQukORBfhR/e0ORk+v81kjfrw8rv0UD7WE3YgR1rcLr8VK6HpHYFFKWsjjDjtnc3RU681F+vhOtPKd3/FdxpRVsyzDsGAnxjomDZVgYlBXh2IzWXJ7IjLBQZ688r5Qnq0U9jRxnuhiSQNG7i2++Ms5PFBjjLcwJUPtCLEb2wIt0rqpcvMkgQ0yozOimU+TJdSQX1YvSWCOtPIGxJlnoEGt6OLNJVDcgFOMrZrF1SU6D/wqtFt9M
  template:
    metadata:
      name: fuzecontact-db-credentials
      namespace: fuzeinfra
