---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fuzesales-db-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    password: AgBmRajAt9yK+wKWMvPtQB3qSSkWHjZUfsLDBLEPoiBAE2VKOGJ8RzZhgtWmhpr28zhDWx2V0WoOQ5/dIIz24FIAojIGYWz3BdM65QAHYeka03Bsg2xa1awqmESsbSf1xNgIYwCIKgeFSTQf/yB56u5hxyhBpTHzIHuFANZF+we2zm+E1apVIzPZpCDkAyzzMTUHhsOXzaCOrsvx8lwmF67ed9u1NH2fa+7JYnxbIsHb6lX8LcgETbUY72ky9eTu5xDvHIObiDZ0sNYTSfJ2b+Z3z5+xgL5hchRPg0BWZMeJx7TK84y+KO/9yb0ad5wSVg/pBXmI17VYR/FAhHBT4fnTAsBH54P08Y9iaAedvl2zYkVY9gUmEHMEGgIF4ImZqb6rmj2Sy5Sohyoet2OmvFsYBU+m9w6TRgSjBzCl9Lh/pzbh+fseKFV+yGMlsehigozkQZFSvkzxb5L98Vte9Qq6vXzTQxbjQFp54X1BxJRi42xrWAxlqUepNFuRRaQQ/npz5IsL0dkj2yhJuZH7Fz5/CuOPgDtKDUYC8DXpGgIcjLZOSB/njKgF2ExwUH35KfJD32dIfdkvw2ztznzlSBCMWEEqfNlOu5HNGS3mpadaUDceht4YWteLrl5vC1+Yr5bRGHTWoCQPOz+5hbGqpH3toF3Tk5pbTWH49y1OuEK9C+e0D7dkJoIqBK686swU51uMvxJITuK3xNywegAp8qtOmtS3rAMrqR/jlWBbRzE8KgwbiI+KvWgq
  template:
    metadata:
      name: fuzesales-db-credentials
      namespace: fuzeinfra
