---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fuzeservice-db-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    password: AgB063JDPYzurKs8jGpg052kHVqzQJXQMh+p2qdNCUw5X+FKieWP9shGB9W4VMeFhEbMl7WfR07C2By20mlBL0MWQoBreE4dInW1vWsJjZ5yfJsyqBXWxrYjCNLJ/2BdmsWrWa9oUUoVQiTdwpour/d0QmLxp0Yaru2X2LJKwzqXzZOlI6XpzAjMwKMLuiYm9sY44EOdF0HNB2u4QnAeOcNY0HDUFCgSGcq4JzrRp8mIsomEVvC0FSndxq5I3crjrcckMBKZdr0QIKByJnAC/o747cqocPsmAG3TKwriApHbavgvlB+3juAvokqLq8bbY15CApWaNLkjmvjO0NP0OnZd2jZzRNvZOk9EhCHrO4vrhGt5pzUCkprnhHKTpktlo3t4RBrhvra4NRSl9YmWlNPG6ztNwZXVLdkyp4d86L7ta08ECmJrpIblZG98Fs8rDJeXtvkWKx0E1Wh0zBc63K+fp/fX4rMZXiog3lCwgFotjfoOKLveiNO3GGcSvx6rQgVkYIqA5fJqwWM6qKS8QfkguPyuNGAQSCvE2ETCF3zc7KRQrlGcekH1PDsPwlASUHTOEVvhPlyC+s97BW/Ez3XlmLU9UwcGwBhP9DoCGpAiOYsZGNaOW/O8EoXcoemwWQUL3yF5xOnoSCMA171zZ8GUbFdourU93oIXZOCw1yOWR8U6ynzFCKrbC8RaWETKYtLvNsa9M+5sdaeUanYcDKhM63JK9pMDwfiCiizesGjvZWJ8J+Joi8WW
  template:
    metadata:
      name: fuzeservice-db-credentials
      namespace: fuzeinfra
