---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fuzehub-db-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    password: AgCdlSI9VjccouZlLEDVQQVvWtOoldxyfSrDdVt/z+lHZEr5SsOgeVqmyG0lfB51pJOY4a9UQUXZtbyAfR2f1K7bVuoyHWPeg2iiwFF6zWxMR6koNiDI2Y+1Gq3H4Jyskj3hzpV+GWYJZCbwWGXMZg8EQ/kSFoBO0aZ0/TVtH61Bdqb+40F0nJV4n5CqGc2pe5bkRcFLGazyVjHb6EMeLkJ25hCYUed12uUsd7qtstk128mRbFDqsckLh8IgR3153B/7i5dO9BfO0izaeprQsmgexLPLhh+w+4jyAlX9W7mA0nZ3HfXWift3AdAkAlxeXBxvZLGUrT+dAP9uWDBEcaan2mGXO3aSFjjIZ0uLAGvyZ15dpcQXCIb0kmCYyv6l4qJKIqWBVcrxGX70YF417L6ZxPfmg1ZR6AfCvoBFE2x5MS1nNJLc1INTYRXahQaoFSBRuVLCo4BnitLNSoer2sn4PNQwIDX2kQHBRqsq+rLQZ4/fzvSA+a9F9cB/DaVllx7XzlCiB1CqHYSqyFstPvDpBDcxcQ8bYHuLfLgW0c9fNDPMm4n1Kq2xDrNsurKigX63lgYatKmjeqdyvKKFll+jnnFEE414iuQaHo7m5pLBPNKKbu7Vo+czmhtO+HTrV4FioH+cjy8Ek7OUBy+HrDKXWIYm+/dX3BxI1oIX2xMpXzVoBSw+zBQwX1hqm7bT8RLEZ3Jpq5abXg1YSFq4FN7T0lKRaKrJfw6NQ+IhsUooO1Wqe/v6/prsBPJ514jsE0U=
  template:
    metadata:
      name: fuzehub-db-credentials
      namespace: fuzeinfra
