---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fuzeagent-a2a-chroma-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    token: AgAvgho2XQto5iAvXUkuYrEyy/F6TLZl1fV/y8JGkGFJ72/QhjYk9o2biz97FG1XoF7ExAkY/dYdw4Dt+6jYbPxEYY+A6WJyivhBhxzTYpVgQIVEduDAs5x3zQlzDdDYxpLj/SHIIHaKXV32V4Hwf8sq/HL69AW60zJOj8RAbgOvdPZzZ2kpfN96nFgauIMJlI+aJ73RMCJVjbBqidD7winZc3F9yZ2msRM10u8D3JwSI5m6YG5s3mUEbdFuxlbRuETQ7BIfCIPLSIDAlV4MS044DnEseWmEbP2UUlO2VzHHLKdEKGN9HD7HkxFftsyQmNcI9JiJZcm40fiHHEnW94545oIuL1uMcapF+8ccdIy9ghZKcfrhMl6NgFuvxpR1w/lMUkR7KsjOBiGXuADY4I30TKVIFJG6VN5LWBv3EcUzlY1opK/ukLnNsuBDJng7XkCTM61HAv2VDt8LR1qwK53znWhmbj6Ky7DHEracMqJFHLOizJ2TlvjPpMuXEwZQlIBj520BpdV22356EXMG5qEE7dDasL52gdk0im3i5qYznrRn7Je5SjUmmoiILdV+yGsZxP9j4oiVnfEjaou9ktszVAL7D6XHI9RN7eD6Ltn8gysJGrO7BUYF4id1hIYTk98K4HArFqF6cI+gIP1qpZZ3ZGMpYUSCo4LnCfhNhnCUsjeo7AXtpoZYOg8916tdP18AnKg+i6BtiEo7JaHoALnTzww0xP8JxnzGi3NmEIPHMbS1sdRfIwQ310lCTpuHdV88bEcSdEqFumj6OOM1qjZf
  template:
    metadata:
      name: fuzeagent-a2a-chroma-credentials
      namespace: fuzeinfra
