---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: handoff-mcp-secret
  namespace: fuzeinfra
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgBg26g03LNLbarjHfJdqag1hlsEjp3RrZkVIUW0Zyk2LASwVs5VT+96EdK3+o8gW2ZFbfAh5Rd0EN2SBkAbu3027KagxN2RFMmGE+SNvCAgVBdJBMaBj9Z6xQ9p67nd0rmBj3z/FlySBXfymJU3PJQw3+g/wNw+CNap5H6Nv/cDh8n3KBKuviNCtHHTJjusKhlcXcrH3ruWj4kZo+bivPw//ZeoKyb97wm9zdxjOM8Hl91xPgwGhM80ievK9+UGOJiDEZQ+Xa7USL4PBGh9yOypOytoZQ1g/3JNxSkAGJtUac6y3kd9EhEjQ1gJ2m9Vw14mFCt9Nqukk/sn9pVYlboemAUlSXhOL0TNgkhcebW42GAQv0+Oy99MM+KEivOSImYSrndBLasQmwmIXek6tNxVcDA5bkn1Z+/9G0C5wI6LOFOFo/r7dFsRJcBZxZdSNtmdt2q2m+cSsNjVuwmAFn1hNni4wRzkD40Ex13jKPAJM9JMpTHCIiC1rxLUSD4tiyOUP99I+Y57svCXY40JfR3nxO6NxvztdK/8YI54Vw3FnkNxBb4fktpYZkc9CNItFLCpxDyF4rlxSACUOfrkPlm7vD/hsgFsxbwtp2bbKJJ/xvDmekea18b9N18g60HDnxT0MrCk2qZy9CFoWisSQTYYWZNv7WFz3vr3BRo7BvT6NrwSoJQwM3J6BfEwycfk6o3HQQfZgD5QtdrsCJYD8ni+24kyGi+gQVUe3+0=
    HANDOFF_MCP_TOKEN: AgC0kMYOk1kpO17GjKPUpRvJr171FbVAdDI0uepoEEEGeKL84ii+GjNJyo1uN6mAbC9UdvzD+UBy2St7E0IFhG6k8Phn3Wkoz7wwOxWl3KuIqKGd4OrkO8M6alCOVsckCD/3onBlPliQM5dTRHnsIOqCu3NFxqHo8gLj3u5CYIOZrJ5fA5iFT2Q3IMsQaTisIlCYe6B1Na/DUkC/4DbCKvhzgCIyt1aJgGdmP/XKT9EZ/Wn7rSdlawZNBGPgCFKFd7vBygBdYYn3Qz+lFN4WHntqmt5gxzUyieHZQUa7ifsLtIQ1NqaDJBdcWZakHSo2vfbXeXhx/X/KDK+5wpHl9ax7lk8PkRmayd8laa5UJBphKynPqoOtLdubkthVk7FomG9KbIrATnmFu4WKdfX1uf1r1MzF16pWD7OfvtZkbdgv8qlZvOjrLOi0K3tlfMshViTXBk2o4br6qAsfoENr/JY1NjOjoNMzB23fOdJvPPdJ9ZQLzUpBgc9SWyhpiWdFXrndNt5Pj4av1Y+REVOvHMoheqECNbduGyTBFJoiySijuglzsqbK938TCOmH5zjhM6ImT//32job+4ovgjaY4XVL3bGpp/SiBAE5AfLJrSzWCs+L7JuPH5P98REJF98LwcpWFtMYMfoHZIuYAdtou1YpEsA9RVC8fzA3ZrdpO9s98dhLnRyFVEktG/oge5bprird0uMdsvwslIdGFxNB7WN9JyjmIKzvPD4BTQJTvG25HeJXUrXT/tDTaVtu4VsB7nMFMXoOOYuf1iyIe57veku4
  template:
    metadata:
      name: handoff-mcp-secret
      namespace: fuzeinfra
    type: Opaque
