---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-ui-oidc
  namespace: fuzeinfra
spec:
  encryptedData:
    CLIENT_SECRET: AgCd248AxesXrqpzpQJDiiMa5CUKJFlBOBpLCDovK0ggiteDQN7bo+DRwmuQmON638vuuHHnrM4KcTwoLa71oZsHXEVYJAkfTbpS8u1E1/q0bCK+QUizSpG24oz9ZWatBB1QMgcpnSj2YkB+z4vKp3jFB2YB+eUNKe2Gvx5BRtGyPyuQ7Gl5nlT7TyxI/H3oD9CLStvcbNrqEsJd1jwQwZ70sJjNYUOTCLLI3XF2KnXly4YjnHoZNzJTCScmwoNIDmA2Vg8m4DEOlWBSekeM4WtKC6dmKDDECVJuNT8lDjmAqC34ndQWK5EL4FgMoKXe92MyFDRM1yoJ0D6+P+u0CbY9nfMjrl8pbFC2z/rTRrxzGriKS+WNnPZsZgr49VI8ysgu9FtV6mj0Eav1dkkA+AlTS2APl6z5R1fnzT8/PzLMRWNpoVbmfmoiyoAY1VFv6ydfpfSLOsrat0m7ZiKwdLwUWg3VUIpq6QnNa9asPjptyE7bNZ8DvVdkSzTFyrfNVFWm4lFM/Oo3lafrOqqErtP3wJBYuvysbqTV5lDOcaYOTxvNMVsQQEcgCVJW+ePIC1Oidtutq/61pShBXkrTWvpsy4GVz9hGXcPxJRLc2pRXQB9K8zIzeombVEh1ysDKRRAfu3X/zfpFqslWqOlVbBfgHE1Faox94Z7xykZfySDGB88LQGvqUNDeQ4l8jkkodikTgU1kV3e0B83+VvX/N0v/6JvWsKLFr40dWM3+Ry0GCgF3p2J726/v4V94fCtQ
  template:
    metadata:
      name: kafka-ui-oidc
      namespace: fuzeinfra
    type: Opaque
