---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-ui-oidc
  namespace: fuzeinfra
spec:
  encryptedData:
    CLIENT_SECRET: AgBIHbVvT7u5j2Qoyh/r3C/Nwbg1Uy4IKG4LlwwafYXon/2PXmbyFz6u+CpOvV+HO81g8Or1d6UC0km/tN80vUBgSYCNglMSGIj+LB9MSc7/nIZVqeG1aNcaxqLrxHKUo69hVijYmDvtW2U5NWEbzWXRbybMTwJpshQkpvbLtTwRlwXt3KZi+VxNzYfgR33mso2lSY/jTr/+22hKogntgvKDzHF1x6JSFZhkdVXjy3A6/bvoiEq/iwABizcPyjo7pYM1AdC++QRPMYOuzoBkl0A5Ps8BTRqVOFrXsmJhs8OmGMlHHtta2VTxvaZ/tTTp3hof/O0AgAi2wHWSfqg18eSoDcVV9kuifP4khGzjWyor8eXJ+SWyCapC65JIIG8DGoklzQDrcD5N/juvBRdRJqT4eJK4MiRQOFuvll2jtRZ7/3ZM04673YhHXqVxP0P1p7p4anss2qX7SnlD/Bl1Jdsp6aqgXCDiV2z0Zg7zUNVS0cfRpQgwIiWXEfcb4tc4J3ulxBTlo+waHXUPzWCAYogbmOf7CFD76S5ctEXFLt3ING4Frx2A99B+1p16fmO1HCimhGjDexkScWm+RJ1U70hEkcGNfk212UDLfwhX+HZ++dhVsbHFUT61HvB+Ko6ab9HnOMtJgaln9da/zEIKsbSShSO11oot8c1WGuMiX15hD7SwqU4xa/oLDFk3eQ7K9ygPoPf+MiHBwZgoVTJKMtdnuO/LmHqBMOprjE4n9qIUmResLRK6Q89x5uLX1OyO6NGFLEcxrt0RJUvZHaHwK7tR0n20kOuCA0vTMpN6PFRz+lh/w1IWYJ/CvXXK3pOFVko=
  template:
    metadata:
      name: kafka-ui-oidc
      namespace: fuzeinfra
    type: Opaque
