---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3
  namespace: fuzeinfra
spec:
  encryptedData:
    LOKI_S3_ACCESS_KEY_ID: AgB+HVxgXD4j0YWZDtffSLpwee/M2A9Yi0pV7x2TIXqEz9Sp2FmVu4t5VunPk/zY97ET3g5fugvpAhtZrTk6sIeaYFO5+apeuJ1oHaiUFwx9xzriVuH1lNE2Kdm8GeBjYG/qyVYray9EjTyB0tLz457qfsNlKNOxu0m/24piNHP+KLFPmBiMbKSxVfX2+sAErRZtNu+60u8t1ZA9TdA47LrSCgDSX8c1r3z1Gj7GB6XJuMNIKFEqz7mqS/SHSsEOXVAtR5FhwIXdWzw2wkTpiWsCQnGzRHOJ477tyjmaRtwSCYFIkGSss5XdgRtYHXHPF3EcSIoMHy58UaC9SAfiJZ4VYq8JQuagT4NDkI3DIgWHkfwVgb759P7GgDAnZwn5oJJYrniQAZos+z3ICtMofvohXsWBi/7aEnkhKdTYk9PVH/Td3IqxsvX3msOYZZhPKvBK9mfCvS0YP7KNmzhUxD5VefxZ9k8+xJq/J7XK7aV2+XftYDQ1bhTr4Ve2aA+fat4EqrrHyLlUZcWBEz/z7FxD1RdonrpOVk8zGG5Gi7nacoVxAvhwoVWI3JIceoPf7gpggjASmwdsOWCSR4GaYZElQm1xB3xgVJADW3s47Gm8eNb1CpPHgTcXHMKEpEFne3MUfO3Yha7apCBGqr1AB/fXw7w3wIYrqTPUHd2Nl1MMYvzUH4kKviVqV8XTcPqR1MHbOOViA1/a5c9Evc1664JwRXFe83u48R+Q6LNtaFG4Ug==
    LOKI_S3_SECRET_ACCESS_KEY: AgAahGKFPftFtynveSGIT1AvL5t50qV15ru0r6b9lwmpBolbvWhn9iswtiCWwvQSI/rN0qmRptJXzyRWk4e7YZLsCAWDqrv/F7mHQM2CidEKWHXEU5eMNdpCc1y+8P4ZM1gNXvW7+D0O8aITGDaCJRaUh8I6BpF7llQNktcAnSOKpsImxQqxAXbyPVhe9q5/pMrfUMaww49z08dNUPeli4C3ZyY9z7rSO1LIXYOsy2M3gvsrZxXoV96R7JOmV7keaCFLRLX+BCr1ypWX3B+lfol3YpqHNwCNuJH7vw3Mf2iSDebGKM58K28Cveg7PQSkHZGTUrrM0H3GfcJeAlN1se00DUv6qQWUe18KQAgnFpw1eHCOHfADCV9DXI9lJBI22Y24ynUrCl2+ugzw3WdDAixQ+Fh5cCKNWtC7pCJKJH7mnGGE9nXgETpRVTjMUh3S3S3S3NXssN830fCtBrxcY3g+CNHGPTbTUNA7qWYieWyw6dwGkwGeMTNcJOj0NZ6LGFqzDI9GjE3H4eZJ1IGlo9hzcp2WbIFuavKrRnDr2fiCnJvwMNsCU4R/WWgCwy/V0qO1ojRjvMEG0OW6qhGayzyJ3mor1sYNBeZF0dwV6V38vOsvPxxeuExPrKX1KJXkt4HOL4RCxYZ4aByBKv1ltkW8RlZHLCE1SEm2wOAlcWRMACmaEeotxv6m7cSYRAUN1gGIgtcfcRPGmOt+47TYV78h4JvTxIwplIpPuKXs0w2BnA==
  template:
    metadata:
      name: loki-s3
      namespace: fuzeinfra
    type: Opaque
