---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mendys-db-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    password: AgCJ88VtmBisdnN5Jsf9CjDfCDXIfoJj18EL7pl0fjsWhdLmtjcRWiV7Tlhal9nBN4ATs4tVBKztOCwWHRtaTZPM3egzyZPXxnZPmtMb5PZyOTU143gYggccEuIHV7ab6/tk7Ds/IVuaXwuOhIT5wRABtyawmRbb+LnrbWnK6oPDfpIgT1EP2W5ehEEm9rhTlGVg/knu7ntZROCi2VXpF0QVX1GdEBSNgBQW29RJ9vqCroqxCnV9lP8F3hkCL7l9faathxJUs7xfcLav+8AKyJThTFb9nuOaDmaePb1F85sSQvle6sUoIjq++DxsuovuPp+lOBk6kZdexggffDMRGN+IkPPolKG646QZfcrqAp0S/fJ8/s5AZ94G1a6y4tIBjX9aL17t7WeKxhhwxKzHMctMENtrmvI1qcmJKaV4kLlYpVKmN3CNqbn5jAojbTrfE0/6nSOohpQ638oz3MtMEDeYUivtvNFSNfHMj5xS27W5oqhUxZBHBf1mFjJJlzliJTZUNwEo/knv16kmIA2voEEtS2TuFskwLBOzvziiZH8/0m8DFDeYSluL2YTQq+q/nJSYEdotDHEiTsu+yzmbuHqHjhD6NGWMEfGjd1ZEZidfZjsnqN3KWqWkeAcMGbqqd+B1cVRKmM9aefeLBL++pPfXFH4HNtCcqfdCboOMiWsD8YxvXXksNXMZ3U5ejx8ij2YIh2gmHZFKqNoSF63bOUIWeq4KtZtxX+Wso1zXSxfVlKk+666OnMVi
  template:
    metadata:
      creationTimestamp: null
      name: mendys-db-credentials
      namespace: fuzeinfra
    type: Opaque
