---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mendys-mongo-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    password: AgCcUHwnl1GRcC0w93saLQicmWV/vsc6hn5zbD+AN6gv3gmTdqGbk2tcF4/SS+dqXo/PDSnCrJybI+DdDGU34iBnzjmTIVX8oZb48alU2jXAnrfs1i/Cmlymmj+Ifr/EoHpmHqYefx+oYImWoflV0oMYLTPNPpLRIPMQjbNOroqyMCGA+krM/CIrsDXU5KIXXqon+IjIDbVAf7x7tNFKQGWB8Yvw3b39DrhPwycsOv6RXHks1SLqgRQ95738XM8CT9nSdzwVuie5Ff38cKo+q8wINg3Ea2uAzInOMEE92xJ+e6RGfRXRMosVrgax7lo6CG+KmmS3zUriwap1Lwds6eFFLs3bK6JDw1d5zvgAfhvbf8uM/RK4nqpWsDqHYK7igEOAdlTAAqxSka0WoHQFUueip3R6jiaXxXLDmsKhQk38RDO6yT6RNTV5EaXFYChS4QOiZjsuzKqTRTYK/WE1eb88KX220Rui54pwWgCgBSkyv01fnxyuKiBZIKVP+WhVtdII9xcKN+P02IhXDsu3JtK5h6rNHNpFagun6b17sU4IkaoD1XZUuM1NOIjSgT1M6fYm/qF/fWo4WVP4g5yGhZruajkhyb4yHeS5nzuQUtZ6ertUVUMLM8Y6MHv7Y0QuR5eIVuWnTjZaczmroGmEAaAKls8kjxOfhRVF+BnXXNq95LKxbXCWgxoF/kEipjdZBtOz31x3tsLEViKYpkVAFMoP3PdBZRxnrIqCSCHhA+czQjTOgmNiSO1R
  template:
    metadata:
      creationTimestamp: null
      name: mendys-mongo-credentials
      namespace: fuzeinfra
    type: Opaque
