---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mendys-wp-db-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    password: AgDKkgYJAn9PACr2PCby4S8YvjBv9m1eIpGVro2spYcyPlZ6h7vtp6+U6mFmPDwCwUgMKSjPtzUqEGgREKOwejGqzxgaqCahcHoano8Y9ZQ9q9GE8Sgoxx/QlBdALb+UBPREPYiv9dMk4FS3OpOnRbrOsQb/zFFgj+z/94tOrIF+FSAyipepkW2rV6SdMvVdQ906HmuIPCpzLqNfRUnhFyhtQgOLgnpyK2leXMfvEY6i6RWJEojKo7l6ClOa1Dio+6PACz20T6d+yXsrQgChzN7XhDXK46Jx6Zez15KJ7AozuwRP9vJPg9L+NEuYZwiwBkN0VsXPKZiigPi0/ccwFiZXScBayjH0LtaHmaF6TIpcSxd9fHqfalDK1Y9EEimniQJHtcqldqoNL1KEzwdDPJ85Lf5o6nWXuKnY8M3AFPSQGPwmaU1a96Ex/qgltF3S0I8IpBwn7aFwwJumrHqt/SSH3xQlD40OmUadjhaVYihJIvYwn60eofGeonNjPDLcbuagJvb+9E3Bv2DoV6rU2pGYjLzWtMcgOhsXU4PJ5df7dzPrAieLy1BBtnw8jrAJVzvak44XARQAs5JSzBRyI+kzZf7RXNX9By3tJF43yvBui+4RK3jzlFkQwuxeXO4v/LYW91H3hSHkUE6cEpv8yeNBwkVRwGu9nW+puzk9B2n++Kp+gpZ6RKzmshAQ64sMpARLDcUkZC1erYOtnu4A5/8ykCduzfdMN29piLnE+wPyKBpMKQKGD4ds8X8ITeTbxE0=
  template:
    metadata:
      creationTimestamp: null
      name: mendys-wp-db-credentials
      namespace: fuzeinfra
    type: Opaque
