---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neo4j-fuzesocial-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    password: AgC8/J9cmj1RzULrdfx+sWhXYfeBqWajWIPzuvfpgR0OQvWt8bwN5R67nUzmLTyEo7h6m8m/YQUppE2waz3MP9Pk7nCGLmXSGrxftOH/ycA8o1OV8UWbjUrX3DBizOSCv9I6sSeketoxNHowPtJsjJmjaZGP54mq2wK/vrh4jU2ho1nFAeQJ8z4rjPBnwZOQyHAA6ZIkK+VVKDeWstzo8FVceLCEZz25Rjdg+m4VCG7uMO7yuMYu4UjJupo2zN7o26X2XH/7yUHbP3knM9vDPoIjfjxNI0IQFLkkdBYgcZYDb7DNvtp6QoEW6K2XcZ71COVu+8cla6DeYFpqQSvn2W37Fypnh8teqMdMXta6crJvXumsWDlk/yuTMORTBC63lfjmPv9yJmCek8efLzFeX53wUV2AMGFr/KJg1CkC0xKYaxlhnCv4ccHRWFrJTQQn+ugxdBcuF8cKGS9BkyGwnLrHUuFvJvgGyLZ+EIjMQKV+c4T4sgLTKWt0bQMwp5fCClbiqCELsUZDpZ0aHFwcpBADGxDnB1QE6Bw1hP/5cMHVOQADbih+2c3CzoTpnDKvVnM5O/XmudntTFrT+dWWPHzn8UWiyZD4FIEqdPVLdqVotPaQ8rPRGsmBirmR8bMh6dlfq62waHieMcOpphgNFujdFY4eRYXA0LKoYmEcWGbVFv8eqwzs2L0gw9MLG3PxKbgBBeeEwu9SqY43xTT5kfD7h3syRSQmGn5aaQ18ZYrW6135/Uz8pAbt
  template:
    metadata:
      name: neo4j-fuzesocial-credentials
      namespace: fuzeinfra
    type: Opaque
