---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: neo4j-fuzeplan-credentials
  namespace: fuzeinfra
spec:
  encryptedData:
    password: AgAIdj9FlEF/ww4uQOptTMl2dBN37OgdexqDIGId42P1VM7iioVjrj4zkdIFobcARFuVrdxpfqfaT+6mwaIS40s81I9HCa8mwMeDxD/OepuaiXlgbErQ8KZZVD6pzQQfFJCN8p3BE+IxvGpVzgiArmY9nZGu1791k6EznUceT62XPnb8pd/EIpVzbDHO8Jh8MKPGpIYD6Zsu3CTNDGa0Sf9OVsneo0wKAoUVUEpIwshgPLbBEv1rocPNmYWdwNq5xKnQk3UjNfP7gDMpoumgSqR634WTVCOw44+0DrmAH5eZt1G9zkxQzRX8Yth9LIVXRKwUPoliz6DauF1wc09cWw+rqU5yRgZ4vMYW40VGzs5facEqT3uxJYE7k95HHZTPzyiAHmrOznKoi5Mv40ZW74dTPkrRWix4MtBcK+iSdSWuFr7GOGhJOYzPJqLCtDXfT3dP8PeD7mwqxTAsVqXkPk+O/KqN3pQD84dORKfcxCPaWpBggN9YOM5w9VQ+LxmR9EDLnyq+omNN6EjfqlmP9cC9/eHRmCUh7m+XMIxUG8QRTAuOsV7I2Ev4SmKq0w0kM8PUtYqfZJaipZS61elyz2s6gIW03Mo+dKf9r8FUFpuvARXN2jdTf8LY/oMgQcH3spka1oD24dK5y8i0J0Wv0KV+i/WtJsPgUBP73VxLa3ur4/yky9QI6YyUbqd25qdrueTzh6U0HpgeYOe15Zg7YXSQ1FmoUZ0VckYsaXU8bgxQpJYvgoxXM+8cyW/xdflO520=
  template:
    metadata:
      creationTimestamp: null
      name: neo4j-fuzeplan-credentials
      namespace: fuzeinfra
    type: Opaque
