version: '3.8'

services:
  shared-nginx:
    image: nginx:alpine
    container_name: fuzeinfra-shared-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:rw
      - nginx_logs:/var/log/nginx
      - nginx_cache:/var/cache/nginx
    networks:
      - FuzeInfra
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
    labels:
      - "traefik.enable=false"  # Disable if using Traefik elsewhere
      - "com.fuzeinfra.service=shared-nginx"
      - "com.fuzeinfra.description=Shared Nginx for Local Development"

networks:
  FuzeInfra:
    external: true
    name: FuzeInfra

volumes:
  nginx_logs:
    name: fuzeinfra_shared_nginx_logs
  nginx_cache:
    name: fuzeinfra_shared_nginx_cache 