server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape robotics application logs
  - job_name: robotics-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: robotics-scraper
          __path__: /var/log/robotics/*.log

  # Scrape Docker container logs
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/?(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'

  # Scrape specific robotics containers
  - job_name: kafka-processor
    static_configs:
      - targets:
          - localhost
        labels:
          job: kafka-processor
          service: unified-kafka-processor
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # Scrape robotics scraper logs  
  - job_name: robot-crawler
    static_configs:
      - targets:
          - localhost
        labels:
          job: robot-crawler
          service: robot-crawler
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/host/*log

  # Kafka logs (if available)
  - job_name: kafka-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: kafka
          __path__: /var/log/robotics/kafka*.log

  # Scrapy logs
  - job_name: scrapy-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: scrapy
          __path__: /var/log/robotics/scrapy*.log

  # Airflow logs
  - job_name: airflow-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: airflow
          __path__: /var/log/robotics/airflow*.log 