server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape generic application logs
  - job_name: application-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: application-logs
          __path__: /var/log/fuzeinfra/*.log

  # Scrape Docker container logs
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/?(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'

  # Scrape infrastructure service containers
  - job_name: infrastructure-services
    static_configs:
      - targets:
          - localhost
        labels:
          job: infrastructure-services
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/host/*log

  # Database logs
  - job_name: database-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: database
          __path__: /var/log/fuzeinfra/postgres*.log

  # Message queue logs
  - job_name: kafka-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: kafka
          __path__: /var/log/fuzeinfra/kafka*.log

  # Monitoring service logs
  - job_name: monitoring-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: monitoring
          __path__: /var/log/fuzeinfra/prometheus*.log

  # Redis logs
  - job_name: redis-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: redis
          __path__: /var/log/fuzeinfra/redis*.log 
