apiVersion: 1

datasources:
  # Prometheus data source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://shared-prometheus:9090
    isDefault: true
    editable: true
    version: 1
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: POST
      queryTimeout: 60s

  # Loki data source
  - name: Loki
    type: loki
    access: proxy
    url: http://shared-loki:3100
    isDefault: false
    editable: true
    version: 1
    basicAuth: false
    withCredentials: false
    jsonData:
      maxLines: 1000
