#!/usr/bin/env python3
"""
Consumer host collision guard.

`terraform/contabo/materialized/consumers.tfvars` is GENERATED by the
`cf-hosts-materialize.yml` auto-PR flow from each consumer repo's own
`deploy/cf/hosts.yaml`. Every label in it gets a Cloudflare Access
application with `decision = "bypass"` / `everyone = true` — i.e. publicly
reachable, with NO Access/auth gate — and the tunnel's catch-all ingress
rule means any Ingress in the cluster is internet-reachable the moment it
exists (terraform/contabo/cloudflare.tf ~line 102-110, *.prod.fuzefront.com
wildcard CNAME).

If a consumer label ever collides with an infra-owned hostname, the merge
would publish an infra-owned service — potentially a raw datastore such as
Elasticsearch or Neo4j — to the public internet with no auth in front of it.
That policy is currently stated only as a COMMENT in consumers.tfvars's own
header ("labels must not collide, no wildcards"); this script makes it an
executable, CI-enforced invariant.

THE COLLISION CONDITION
------------------------
A consumer label becomes the FQDN `<label>.prod.fuzefront.com` (dots in the
label nest normally — `api.keys` -> `api.keys.prod.fuzefront.com`). An infra
route with $routes key `elasticsearch` owns the FQDN
`elasticsearch.prod.fuzefront.com`. Both live under the identical apex
(`helm/fuzeinfra` values-contabo.yaml `global.domain` == cloudflare.tf's
`local.prod_domain`, both "prod.fuzefront.com"), so a collision exists IFF
the full label string is EQUAL (case-insensitively) to an infra-owned
subdomain string — not merely "shares a first dotted segment".

`api.keys` does NOT collide with infra-owned `keys`-less routes (there are
none) and would not collide even if `keys` WERE infra-owned, because the
resulting name `api.keys.prod.fuzefront.com` is a distinct hostname from
`keys.prod.fuzefront.com` — a sibling label nested one level under a
completely different (consumer-chosen) apex-relative name, not the same
record. Conversely, a label that is *exactly* `elasticsearch` collides,
because it resolves to the exact same FQDN Traefik already routes for the
infra Elasticsearch UI — Cloudflare's tunnel rule / Access app would end up
either duplicating or shadowing the infra-owned host for that one name.
Dotted labels are therefore handled correctly by simple equality: no special
"first segment" logic is needed or wanted — checking first-segment-only would
produce FALSE positives on exactly the dotted labels the platform already
relies on (`api.keys`, `api.fuzepicker`).

SOURCES OF INFRA-OWNED HOSTNAMES (derived at check time, never hand-copied)
----------------------------------------------------------------------------
1. `helm/fuzeinfra/templates/ingress.yaml` — the `$routes` dict keys.
2. `helm/fuzeinfra/templates/neo4j-ingress.yaml` — the two hardcoded
   `(dict "root" . "sub" "...")` host subs (`neo4j`, `neo4j-bolt`).
3. `terraform/contabo/cloudflare.tf` — the `launcher_services` map keys.
   These are services with an App Launcher bookmark tile (some, like
   `litellm`/`unleash`/`authentik`/`argocd`, are routed by a DIFFERENT
   chart's Ingress, not fuzeinfra's own — they are still infra/platform
   -owned names on the same apex and must not be claimable by a consumer).

This is intentionally read-only static parsing (regex over known,
comment-documented block shapes) — no `helm template`, no `terraform plan`,
no cluster, no network. All three source files are owned/edited by other
concurrent work; this script only ever reads them.

Exit codes:
  0 = clean (no collision, no wildcard label)
  1 = policy violation — see stdout for the offending label(s)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
CONSUMERS_TFVARS = REPO_ROOT / "terraform" / "contabo" / "materialized" / "consumers.tfvars"
INGRESS_YAML = REPO_ROOT / "helm" / "fuzeinfra" / "templates" / "ingress.yaml"
NEO4J_INGRESS_YAML = REPO_ROOT / "helm" / "fuzeinfra" / "templates" / "neo4j-ingress.yaml"
CLOUDFLARE_TF = REPO_ROOT / "terraform" / "contabo" / "cloudflare.tf"
TEMPLATES_DIR = REPO_ROOT / "helm" / "fuzeinfra" / "templates"
VALUES_YAML = REPO_ROOT / "helm" / "fuzeinfra" / "values.yaml"

_LABEL_LINE_RE = re.compile(r'^"([^"]+)"\s*=\s*"([^"]+)"')
_QUOTED_KEY_RE = re.compile(r'^\s*"([a-zA-Z0-9._-]+)"')
_SUB_RE = re.compile(r'"sub"\s+"([a-zA-Z0-9._-]+)"')


def parse_consumer_labels(path: Path) -> dict[str, str]:
    """Parse consumers.tfvars into {label: owning_repo}."""
    if not path.exists():
        return {}
    registry: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        m = _LABEL_LINE_RE.match(line.strip())
        if m:
            registry[m.group(1)] = m.group(2)
    return registry


def extract_ingress_routes_keys(path: Path) -> set[str]:
    """Derive the infra-owned subdomain set from ingress.yaml's `$routes` dict.

    The dict is declared as:
        {{- $routes := dict
          "grafana"    (dict ...)
          "prometheus" (dict ...)
        -}}
    Bounded by the `$routes := dict` opener and the closing `-}}` on its own
    line, so a quoted key anywhere ELSE in the file (e.g. inside a comment or
    an unrelated dict) is never picked up.
    """
    if not path.exists():
        raise ValueError(f"{path}: does not exist — has ingress.yaml moved?")
    text = path.read_text(encoding="utf-8")
    start = text.find("$routes := dict")
    if start == -1:
        raise ValueError(f"{path}: '$routes := dict' not found — has the Ingress template moved?")
    end = text.find("\n-}}", start)
    if end == -1:
        raise ValueError(f"{path}: could not find the closing '-}}}}' of the $routes dict")
    block = text[start:end]

    keys: set[str] = set()
    for line in block.splitlines()[1:]:  # skip the "$routes := dict" line itself
        m = _QUOTED_KEY_RE.match(line)
        if m:
            keys.add(m.group(1).lower())
    if not keys:
        raise ValueError(f"{path}: parsed zero keys out of the $routes dict — parser is broken")
    return keys


def extract_neo4j_hosts(path: Path) -> set[str]:
    """Derive {'neo4j', 'neo4j-bolt'} from neo4j-ingress.yaml's `"sub" "..."` refs."""
    if not path.exists():
        raise ValueError(f"{path}: does not exist — has neo4j-ingress.yaml moved?")
    text = path.read_text(encoding="utf-8")
    subs = {m.group(1).lower() for m in _SUB_RE.finditer(text)}
    if not subs:
        raise ValueError(f"{path}: parsed zero 'sub' hosts — has neo4j-ingress.yaml moved?")
    return subs


def extract_launcher_service_keys(path: Path) -> set[str]:
    """Derive the infra-owned subdomain set from cloudflare.tf's `launcher_services` map.

    Bounded by the `launcher_services = {` opener and its matching closing
    brace (a line that is exactly `  }` at the same 2-space indent as the
    opener) so nothing from a neighbouring map (e.g. `launcher_url_overrides`)
    leaks in.
    """
    if not path.exists():
        raise ValueError(f"{path}: does not exist — has cloudflare.tf moved?")
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    start_idx = None
    for i, line in enumerate(lines):
        if re.match(r'^\s*launcher_services\s*=\s*\{\s*$', line):
            start_idx = i
            break
    if start_idx is None:
        raise ValueError(f"{path}: 'launcher_services = {{' not found — has it moved/renamed?")

    opener_indent = len(lines[start_idx]) - len(lines[start_idx].lstrip(" "))
    closer = " " * opener_indent + "}"
    end_idx = None
    for j in range(start_idx + 1, len(lines)):
        if lines[j] == closer:
            end_idx = j
            break
    if end_idx is None:
        raise ValueError(f"{path}: could not find the closing brace of launcher_services")

    keys: set[str] = set()
    for line in lines[start_idx + 1:end_idx]:
        stripped = line.strip()
        if stripped.startswith("#"):
            continue
        m = _QUOTED_KEY_RE.match(line)
        if m:
            keys.add(m.group(1).lower())
    if not keys:
        raise ValueError(f"{path}: parsed zero keys out of launcher_services — parser is broken")
    return keys


def extract_template_sub_hosts(templates_dir: Path = TEMPLATES_DIR) -> set[str]:
    """Every `"sub" "<name>"` host declared by ANY chart template.

    `$routes` is not the whole story. a2a-relay.yaml, a2a-gateway.yaml and
    handoff-mcp.yaml each declare their own Ingress via `fuzeinfra.host` with a
    literal `"sub"`, so deriving only from `$routes` + neo4j-ingress.yaml leaves
    `relay`, `a2a-gateway` and `mcp-handoff` unreserved — and `relay` fronts an
    unauthenticated public WebSocket endpoint. Scanning every template catches
    those uniformly and picks up any future per-service Ingress for free.
    """
    if not templates_dir.is_dir():
        raise ValueError(f"{templates_dir}: not a directory — has the chart moved?")
    hosts: set[str] = set()
    for path in sorted(templates_dir.rglob("*")):
        if path.suffix not in {".yaml", ".yml", ".tpl"} or not path.is_file():
            continue
        for m in _SUB_RE.finditer(path.read_text(encoding="utf-8")):
            hosts.add(m.group(1).lower())
    if not hosts:
        raise ValueError(
            f"{templates_dir}: parsed zero 'sub' hosts across all templates — parser is broken"
        )
    return hosts


def _camel_to_kebab(name: str) -> str:
    """kafkaUi -> kafka-ui, a2aRelay -> a2a-relay, mongoExpress -> mongo-express."""
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def extract_chart_service_names(path: Path = VALUES_YAML) -> set[str]:
    """Every service the chart defines, whether or not it is currently PUBLISHED.

    This is the source that makes de-publication safe. When elasticsearch and
    chromadb were removed from `$routes` and `launcher_services` (because raw
    datastore APIs should not be reachable from the internet), deriving only from
    the published sources silently RELEASED those hostnames — a consumer repo's
    auto-PR could then claim `elasticsearch.prod.fuzefront.com` with a `bypass`
    (no Cloudflare Access) policy. Un-publishing a service must never hand its
    name away.

    A top-level values key owning an `enabled` gate is the durable fact;
    publication is a policy toggle layered on top. Both the camelCase key and its
    kebab-case hostname form are reserved — over-reserving costs a consumer one
    rename, under-reserving costs a public datastore.
    """
    import yaml  # local import: keeps the checker importable without PyYAML for --help

    if not path.exists():
        raise ValueError(f"{path}: does not exist — has values.yaml moved?")
    doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    names: set[str] = set()
    for key, value in doc.items():
        if isinstance(value, dict) and "enabled" in value:
            names.add(key.lower())
            names.add(_camel_to_kebab(key))
    if not names:
        raise ValueError(f"{path}: parsed zero gated services — parser is broken")
    return names


def derive_infra_owned_hosts(
    ingress_path: Path = INGRESS_YAML,
    neo4j_path: Path = NEO4J_INGRESS_YAML,
    cloudflare_tf_path: Path = CLOUDFLARE_TF,
    templates_dir: Path = TEMPLATES_DIR,
    values_path: Path = VALUES_YAML,
) -> dict[str, str]:
    """Union every source into {hostname: source_description}.

    Ordered most-specific-first so the reported source is the most useful one.
    """
    owned: dict[str, str] = {}
    for host in extract_ingress_routes_keys(ingress_path):
        owned.setdefault(host, f"{ingress_path.name} $routes")
    for host in extract_neo4j_hosts(neo4j_path):
        owned.setdefault(host, f"{neo4j_path.name}")
    for host in extract_template_sub_hosts(templates_dir):
        owned.setdefault(host, "a chart template's own Ingress")
    for host in extract_launcher_service_keys(cloudflare_tf_path):
        owned.setdefault(host, "cloudflare.tf launcher_services")
    for host in extract_chart_service_names(values_path):
        owned.setdefault(host, "values.yaml (reserved: a chart service, published or not)")
    return owned


def check(
    consumers_path: Path = CONSUMERS_TFVARS,
    ingress_path: Path = INGRESS_YAML,
    neo4j_path: Path = NEO4J_INGRESS_YAML,
    cloudflare_tf_path: Path = CLOUDFLARE_TF,
    templates_dir: Path = TEMPLATES_DIR,
    values_path: Path = VALUES_YAML,
) -> list[str]:
    """Return a list of violation messages (empty = clean)."""
    violations: list[str] = []
    infra_owned = derive_infra_owned_hosts(
        ingress_path, neo4j_path, cloudflare_tf_path, templates_dir, values_path
    )
    labels = parse_consumer_labels(consumers_path)

    for label, repo in labels.items():
        if label == "*" or "*" in label:
            violations.append(
                f"POLICY: label '{label}' (declared by {repo}) is a wildcard — "
                "consumers.tfvars policy forbids wildcard labels."
            )
            continue

        normalized = label.lower()
        if normalized in infra_owned:
            source = infra_owned[normalized]
            violations.append(
                f"COLLISION: label '{label}' (declared by {repo}) collides with the "
                f"infra-owned host '{normalized}.prod.fuzefront.com' (owned via {source}). "
                "Publishing this label would give a consumer's un-gated ('bypass') "
                "Cloudflare Access app the same public hostname as an infra service."
            )

    return violations


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--consumers-tfvars", type=Path, default=CONSUMERS_TFVARS)
    parser.add_argument("--ingress-yaml", type=Path, default=INGRESS_YAML)
    parser.add_argument("--neo4j-ingress-yaml", type=Path, default=NEO4J_INGRESS_YAML)
    parser.add_argument("--cloudflare-tf", type=Path, default=CLOUDFLARE_TF)
    args = parser.parse_args()

    try:
        violations = check(
            consumers_path=args.consumers_tfvars,
            ingress_path=args.ingress_yaml,
            neo4j_path=args.neo4j_ingress_yaml,
            cloudflare_tf_path=args.cloudflare_tf,
        )
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if violations:
        print("Consumer host collision guard: FAILED\n")
        for v in violations:
            print(f"  - {v}")
        print(
            "\nFix: remove/rename the offending label in the declaring repo's "
            "deploy/cf/hosts.yaml and re-trigger the cf-hosts-declare dispatch. "
            "See governance/cf-host-declaration.md."
        )
        return 1

    print("Consumer host collision guard: OK — no collisions, no wildcard labels.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
