{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fuzeinfra.secretName" . }}
  labels:
    {{- include "fuzeinfra.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.credentials.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.credentials.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.credentials.postgres.db | quote }}
  MONGODB_USER: {{ .Values.credentials.mongodb.user | quote }}
  MONGODB_PASSWORD: {{ .Values.credentials.mongodb.password | quote }}
  NEO4J_USER: {{ .Values.credentials.neo4j.user | quote }}
  NEO4J_PASSWORD: {{ .Values.credentials.neo4j.password | quote }}
  NEO4J_AUTH: {{ printf "%s/%s" .Values.credentials.neo4j.user .Values.credentials.neo4j.password | quote }}
  RABBITMQ_USER: {{ .Values.credentials.rabbitmq.user | quote }}
  RABBITMQ_PASSWORD: {{ .Values.credentials.rabbitmq.password | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.credentials.grafana.adminPassword | quote }}
  AIRFLOW_ADMIN_USER: {{ .Values.credentials.airflow.adminUser | quote }}
  AIRFLOW_ADMIN_PASSWORD: {{ .Values.credentials.airflow.adminPassword | quote }}
  AIRFLOW_FERNET_KEY: {{ .Values.credentials.airflow.fernetKey | quote }}
{{- end }}
