#!/usr/bin/env python3
"""fuze-code-review verdict gate — the ONE decision that may fire `gh pr review --approve`.

WHY THIS EXISTS. `fuze-code-review.yml` asks an LLM (via fuze-code-action) to review a PR
diff and, when the review is genuinely clean, submit an APPROVING review so a bot-authored
PR can satisfy `required_approving_review_count: 1` + `require_last_push_approval: true`
without a human. An approval step that fires unconditionally is WORSE than no review gate at
all, because it LOOKS like a gate and is not — this fleet has spent weeks removing exactly
that shape (`|| true`, `continue-on-error`, a check that passes by not running). This script
is the single place that decides approve / request_changes / comment / abstain, so the
workflow itself never has to parse LLM output inline.

THE CONTRACT. The reviewer LLM is instructed to emit, after its prose, a JSON object between
two sentinel lines carrying a per-run NONCE:

    ===FUZE_REVIEW_VERDICT_JSON:<nonce>===
    {"verdict": "approve|request_changes|comment", "summary": "...", "findings": [...]}
    ===END_FUZE_REVIEW_VERDICT_JSON:<nonce>===

The nonce is generated by the WORKFLOW at run time, after the PR diff is already fixed, and
is never predictable from the diff content — so a PR whose diff contains a forged sentinel
block (prompt injection via a file that quotes this exact contract) cannot forge a match
without also guessing 128 bits of randomness drawn after that diff was written. The LAST
occurrence of the nonce-scoped block is used, which is a second, independent line of defense:
even a lucky nonce match earlier in the transcript (e.g. the model quoting the instructions
back) is expected to be superseded by the model's actual answer at the end.

FAIL-CLOSED RULES, encoded as data rather than left to the workflow's YAML `if:` conditions,
so they can be unit-tested directly and mutation-tested (flip any one of them and a test
must fail):

  1. fuze-code-action's own `conclusion` must be "success". Anything else (the provider
     chain was exhausted, errored, or never started) is an ABSTAIN — "no review was
     produced", never "clean".
  2. The sentinel block must be present exactly once for the given nonce, and must contain
     valid JSON with the exact required shape. Missing, duplicated-with-different-content,
     malformed, or schema-violating is an ABSTAIN. UNPARSEABLE IS NOT CLEAN.
  3. `verdict` must be one of the three known literal values. Anything else is an ABSTAIN.
  4. `verdict == "approve"` is only self-consistent when `findings` is an empty list. A
     model claiming "approve" while also listing findings is a contradiction, not a clean
     review — ABSTAIN (this also defends against a truncated / merged response where two
     answers got concatenated).
  5. A PR touching `.github/workflows/**`, `.github/actions/**`, `workflow-templates/**`,
     `governance/**`, `scripts/apply_ruleset.sh`, or `scripts/bootstrap/**` (the approval
     machinery and the org's governance surface) NEVER gets an automatic approval, no matter
     what the model said — downgraded to "comment" so a human is pulled in. This is a
     structural rule, checked against the actual changed-file list computed by the workflow
     from `git diff`, NOT against anything the model claims about its own diff — a
     self-approving change to the approval machinery must never be able to talk itself past
     this check.

  6. A `mode == "declined"` result on a PR that touches that same sensitive surface is the
     workflow-self-modification guard (claude-code-action refuses to review a PR that changes
     the workflow invoking it) — BY DESIGN, not a failure. It is DEFERRED to a non-approving,
     non-blocking "comment" (the review runs post-merge on the default branch) rather than
     abstained, so a legitimate workflow change is not permanently wedged against a gate that
     structurally cannot run on it. Guarded on BOTH the declined mode AND the sensitive-file
     change, never on `mode` alone: a decline without such a change still fails closed. A
     swallowed provider error does NOT reach this branch as a decline — classify.sh surfaces
     it as an availability failure — so a deferral can never mask a real fault.

Exit code is not the interface; call `decide()` from the workflow's own python step, or run
this file with the documented env vars to have it write GITHUB_OUTPUT directly (see `main`).
"""
from __future__ import annotations

import json
import os
import re
import secrets as _secrets_mod  # nonce generation; unrelated to GitHub Secrets
import sys

VALID_VERDICTS = ("approve", "request_changes", "comment")
DECISIONS = (
    "approve", "request_changes", "comment", "abstain", "superseded", "outage", "skip",
)

# Decisions that always pass the required check. `comment` is deliberately ABSENT:
# it passes only as a downgraded approve or a guard deferral -- see check_for().
ALWAYS_PASS = frozenset({"approve", "superseded", "outage", "skip"})


def check_for(result: dict) -> str:
    """pass | fail -- the approve-or-fail verdict the required check exits on.

    THE SINGLE PLACE this is decided, and previously it did not exist at all: the script
    wrote `decision` and `body` but never `check`, while the workflow gates on
    `if [ "$CHECK" = "fail" ]`. `$CHECK` was therefore always empty and that line never
    fired -- observed on PR #1207, where runs 449 and 453 concluded `success` while the
    verdict was "COMMENT ONLY -- not an approval". The required check has been vacuous,
    contrary to required-checks.json's `can_fail: true`.

    The mapping is the workflow header's APPROVE-OR-FAIL CONTRACT, verbatim:

      PASS  a clean `approve`; an `approve` DOWNGRADED to a comment on a CI/governance
            PR (it keys on the MODEL verdict, not on which gh command ran -- keying it
            on the downgrade would deadlock every governance PR, this one included); a
            self-modification-guard DEFERRAL; a credit/quota AVAILABILITY OUTAGE (the
            owner's stated exception); an environmental SKIP.
      FAIL  `request_changes`; a model `comment` on a NON-sensitive PR -- not an
            approval, and precisely what triggers fuze-ci-autofix's bounded loop; a
            genuine ABSTAIN.

    The subtlety worth stating: a bare `comment` FAILS. Treating every `comment` as a
    pass would silence the auto-fix loop entirely, which is the opposite of the mandate.
    An unrecognized decision fails, so a future decision added without thinking about
    this function blocks rather than waves through.
    """
    decision = result["decision"]
    if decision in ALWAYS_PASS:
        return "pass"
    if decision == "comment":
        return "pass" if (result.get("downgraded") or result.get("deferred")) else "fail"
    return "fail"


def make_nonce() -> str:
    """A fresh, unpredictable-in-advance token for one review run's sentinel block."""
    return _secrets_mod.token_hex(16)


def _sentinel_pattern(nonce: str) -> re.Pattern:
    start = re.escape(f"===FUZE_REVIEW_VERDICT_JSON:{nonce}===")
    end = re.escape(f"===END_FUZE_REVIEW_VERDICT_JSON:{nonce}===")
    # DOTALL so the JSON body (which we do not expect to contain newlines, but must not
    # silently mis-parse if a model pretty-prints it) is captured in full. Non-greedy so a
    # transcript containing more than one nonce-scoped block still yields exactly the
    # separate blocks in order, rather than one span from the first start to the last end.
    return re.compile(f"{start}(.*?){end}", re.DOTALL)


def extract_verdict_json(result_text: str, nonce: str) -> tuple[dict | None, str]:
    """Find the LAST nonce-scoped sentinel block in `result_text` and parse it as JSON.

    Returns (parsed_dict_or_None, reason). `reason` is always populated (even on success,
    for logging) and is never assumed to contain secrets — it may itself echo back an
    attacker-controlled snippet, so callers must not treat it as trusted markup, only as a
    log line.
    """
    if not result_text:
        return None, "reviewer produced no output at all"
    if not nonce:
        return None, "internal error: no nonce was supplied to search for"

    matches = _sentinel_pattern(nonce).findall(result_text)
    if not matches:
        return None, "no verdict sentinel block found for this run's nonce"

    # LAST occurrence wins — see module docstring's second line of defense.
    raw = matches[-1].strip()
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        return None, f"verdict block is not valid JSON: {exc}"

    if not isinstance(parsed, dict):
        return None, "verdict block did not decode to a JSON object"

    verdict = parsed.get("verdict")
    if verdict not in VALID_VERDICTS:
        return None, f"verdict field is not one of {VALID_VERDICTS!r}: {verdict!r}"

    findings = parsed.get("findings")
    if not isinstance(findings, list):
        return None, "findings field is missing or not a JSON array"
    for f in findings:
        if not isinstance(f, dict) or "description" not in f:
            return None, "a findings entry is not an object with a description"

    if verdict == "approve" and findings:
        return None, (
            "schema violation: verdict=approve but findings is non-empty — a clean "
            "verdict and reported findings are mutually exclusive"
        )

    summary = parsed.get("summary")
    if not isinstance(summary, str):
        summary = ""

    return {"verdict": verdict, "summary": summary, "findings": findings}, "ok"


def decide(action_conclusion: str, result_text: str, nonce: str,
           sensitive_files: list[str], mode: str = "", job_result: str = "",
           ready: str = "", availability: str = "") -> dict:
    """The single decision point. Returns a dict with keys: decision, reason, verdict,
    summary, findings, downgraded (bool: true iff a model "approve" was overridden by the
    sensitive-files rule), deferred (bool: true iff the review was legitimately deferred by
    the workflow-self-modification guard — see rule 6 below).

    `decision` is always one of DECISIONS. Only `decision == "approve"` may ever result in
    the workflow calling `gh pr review --approve` — every other value must not.
    """
    # RULE 0 — A CANCELLED RUN WAS SUPERSEDED; IT IS NOT A FAILED REVIEW.
    # Concurrency cancels the in-flight run whenever a new commit lands, so every push
    # during a review produces one cancelled run. Routed through the abstain branch below
    # it posted "No verdict was reached — this run is NOT an approval … reported as a
    # failed check deliberately", which reads exactly like a provider outage. Five such
    # comments landed across FuzeInfra#1188 and #1207, every one of them caused by the
    # author's own next push. That is not a harmless nit: the whole point of the abstain
    # text is to make a review that COULD NOT RUN impossible to mistake for a clean one,
    # and a channel that cries wolf on every push trains readers to skim past the real thing.
    #
    # Keyed on the JOB's result, which GitHub sets, and never on an empty
    # `action_conclusion`: a skipped or never-started review job also yields an empty
    # conclusion, and that must keep failing closed as an abstain
    # (test_empty_conclusion_abstains pins it). Only "cancelled" is a supersede.
    #
    # Safe to pass the check: a cancelled run is always superseded by a newer run on a
    # newer SHA, and GitHub evaluates required checks against the head SHA — so this
    # verdict can never be the one a merge relies on. It posts NOTHING.
    if job_result == "cancelled":
        return {
            "decision": "superseded",
            "reason": (
                "the review job was cancelled, which on this workflow means a newer commit "
                "superseded it. A newer run is reviewing that commit; this one has nothing "
                "to say and posts nothing."
            ),
            "verdict": None, "summary": "", "findings": [], "downgraded": False,
            "deferred": False,
        }

    # RULE 0b — NOTHING TO REVIEW IS AN ENVIRONMENTAL SKIP, NOT A VERDICT.
    # The review job gates its steps on `ready == 'true'`; when there is no LLM credential
    # or no reviewable diff it never runs, leaving an EMPTY conclusion. Routed through the
    # abstain branch below, a repo with no credential configured would block every PR
    # forever on a defect that is not in the PR. The workflow header lists this as a PASS.
    #
    # Matched on the exact string "false" (the only other value the workflow emits), NOT on
    # `ready != "true"`. That direction matters: an UNSET or unrecognised value must fall
    # through to the conclusion checks and end up abstaining, because a skip PASSES -- if a
    # missing env var meant skip, deleting one line from the workflow would silently make
    # this gate vacuous again, which is the exact bug being fixed here.
    if ready == "false":
        return {
            "decision": "skip",
            "reason": (
                "the review job reported nothing to review (no LLM credential configured, "
                "or no reviewable diff). That is environmental, not a defect in this PR, so "
                "the check passes; see the review job log for which."
            ),
            "verdict": None, "summary": "", "findings": [], "downgraded": False,
            "deferred": False,
        }

    if action_conclusion != "success":
        # RULE 0c — A CLASSIFIED CREDIT/QUOTA OUTAGE PASSES. The owner's stated exception:
        # "fuze-code-review becomes a mandatory check UNLESS the failure is a credit
        # outage." Keyed on the action's `availability` output, which is true ONLY when
        # every rung failed on a classified credit/quota/429/5xx signal (classify.sh exit
        # 1) -- never on a task failure, and derived from the per-rung classify codes
        # rather than by grepping logs.
        #
        # Exact "true" only, so an unset or unrecognised value stays an abstain. The action
        # documents its own output as failing closed on an unknown failure ("treating it as
        # real rather than as an outage"); reading it any more loosely here would undo that
        # at the one place it decides whether a PR can merge.
        #
        # Checked AFTER the deferral below only in the sense that the deferral is a
        # `neutral` conclusion with mode=declined, which never carries availability=true --
        # the two cannot both apply.
        if availability == "true":
            return {
                "decision": "outage",
                "reason": (
                    "every provider rung failed on a classified credit/quota/availability "
                    "signal, not on the review itself. The owner's exception: a vendor "
                    "outage does not block a PR. No review was produced, so this is not an "
                    "approval either -- it comments and passes."
                ),
                "verdict": None, "summary": "", "findings": [], "downgraded": False,
                "deferred": False,
            }

        # RULE 6 — WORKFLOW-SELF-MODIFICATION GUARD IS A DEFERRAL, NOT A FAILURE.
        # claude-code-action deliberately DECLINES to review a PR that modifies the workflow
        # file invoking it (every workflow-migration PR trips it); fuze-code-action reports
        # that as mode == "declined". Nothing ran and nothing is broken — the review runs
        # post-merge on the default branch — so turning the required check red there would
        # permanently wedge every legitimate workflow change against a gate that structurally
        # cannot run on it. Such a decline is DEFERRED (a non-approving, non-blocking
        # "comment") rather than abstained.
        #
        # Guarded on BOTH signals, never on `mode` alone: the decline must coincide with the
        # PR actually touching the sensitive CI/governance surface (the exact precondition for
        # the guard, computed by the workflow from `git diff`). A "declined" with no such
        # change is not the guard but an unexplained no-op, and still fails closed as an
        # abstain. A swallowed provider error no longer reaches here as a decline at all —
        # classify.sh surfaces it as an availability failure — so this branch cannot mask a
        # real auth/quota fault as a benign deferral.
        if mode == "declined" and sensitive_files:
            return {
                "decision": "comment",
                "reason": (
                    "review deferred by claude-code-action's workflow-self-modification "
                    "guard: this PR changes CI/governance files (" + ", ".join(sensitive_files)
                    + "), which the reviewer refuses to run against on-PR by design. The review "
                    "runs post-merge on the default branch. This is NOT a review failure and "
                    "does not block the check; the required gates and human review still apply."
                ),
                "verdict": None, "summary": "", "findings": [], "downgraded": False,
                "deferred": True,
            }
        return {
            "decision": "abstain",
            "reason": (
                f"fuze-code-action conclusion was {action_conclusion!r}, not 'success' — no "
                "review was produced, so none can be approved. See the per-rung "
                "'fuze-code-action' notices in the job log for the specific classification "
                "(availability / task / declined) and, on an availability failure, the named "
                "provider error that triggered it."
            ),
            "verdict": None, "summary": "", "findings": [], "downgraded": False,
            "deferred": False,
        }

    parsed, reason = extract_verdict_json(result_text, nonce)
    if parsed is None:
        return {
            "decision": "abstain",
            "reason": f"reviewer output was unusable: {reason}",
            "verdict": None, "summary": "", "findings": [], "downgraded": False,
        }

    verdict = parsed["verdict"]
    findings = parsed["findings"]
    summary = parsed["summary"]

    if verdict == "approve" and sensitive_files:
        return {
            "decision": "comment",
            "reason": (
                "the model's verdict was 'approve', but this PR touches CI/governance "
                "files (" + ", ".join(sensitive_files) + "). A self-approving change to "
                "the approval machinery deserves a human — auto-approve is disabled for "
                "this class of change regardless of review outcome."
            ),
            "verdict": verdict, "summary": summary, "findings": findings, "downgraded": True,
        }

    return {
        "decision": verdict,
        "reason": "ok",
        "verdict": verdict, "summary": summary, "findings": findings, "downgraded": False,
    }


def render_body(result: dict, mode: str, vendor: str) -> str:
    """Human-readable GitHub review body for the decision `result` from decide()."""
    lines = ["## fuze-code-review — automated verdict", ""]

    if result["decision"] == "outage":
        lines.append("**Provider outage — the check passes, but this is NOT an approval.**")
        lines.append("")
        lines.append(result["reason"])
        lines.append("")
        lines.append(
            "_The required gates and human review still apply. Re-run this check once the "
            "provider recovers if you want an actual review on this commit._"
        )
        return "\n".join(lines)

    if result["decision"] == "skip":
        lines.append("**Not reviewed this run — environmental, not a defect in this PR.**")
        lines.append("")
        lines.append(result["reason"])
        return "\n".join(lines)

    if result["decision"] == "superseded":
        # Never posted — the workflow short-circuits before any gh call. Rendered only so
        # every decision has a body and the job log can show why nothing was said.
        lines.append("**Superseded — nothing posted.**")
        lines.append("")
        lines.append(result["reason"])
        return "\n".join(lines)

    if result["decision"] == "abstain":
        lines.append("**No verdict was reached — this run is NOT an approval.**")
        lines.append("")
        lines.append(result["reason"])
        lines.append("")
        lines.append(
            "This is reported as a failed check deliberately: a review that could not "
            "run must never be silently indistinguishable from a clean one."
        )
        return "\n".join(lines)

    if result.get("deferred"):
        lines.append("**Review deferred — this is not a failure.**")
        lines.append("")
        lines.append(result["reason"])
        lines.append("")
        lines.append(
            "_Only the automated AI review is deferred; the required gates and human "
            "review still gate this PR. The review runs on the post-merge commit on the "
            "default branch, which no longer modifies the reviewer's own workflow._"
        )
        return "\n".join(lines)

    if result["downgraded"]:
        lines.append("**Human review required — auto-approve disabled for this PR.**")
        lines.append("")
        lines.append(result["reason"])
        lines.append("")

    summary = result.get("summary") or "(no summary provided)"
    lines.append(f"**Summary:** {summary}")
    lines.append("")

    findings = result.get("findings") or []
    if findings:
        lines.append("**Findings:**")
        for f in findings:
            path = f.get("path") or "(unspecified path)"
            line_no = f.get("line")
            loc = f"{path}:{line_no}" if line_no not in (None, "") else path
            lines.append(f"- `{loc}` — {f.get('description', '')}")
        lines.append("")

    decision_label = {
        "approve": "APPROVED — no blocking findings.",
        "request_changes": "CHANGES REQUESTED — see findings above.",
        "comment": "COMMENT ONLY — not an approval.",
    }[result["decision"]]
    lines.append(f"**Verdict:** {decision_label}")
    lines.append("")
    lines.append(f"_Served by fuze-code-action (mode={mode or 'unknown'}, vendor={vendor or 'unknown'})._")
    return "\n".join(lines)


def _write_github_output(decision: dict, body: str) -> None:
    out_path = os.environ.get("GITHUB_OUTPUT")
    if not out_path:
        print(json.dumps({
            "decision": decision["decision"],
            "check": check_for(decision),
            "reason": decision["reason"],
        }))
        return
    delim = f"FUZE_REVIEW_BODY_{_secrets_mod.token_hex(8)}"
    with open(out_path, "a", encoding="utf-8") as fh:
        fh.write(f"decision={decision['decision']}\n")
        # `check` is what the workflow's decisive line exits on. Writing it is the whole
        # point: without this row the step reads an empty $CHECK and never fails.
        fh.write(f"check={check_for(decision)}\n")
        fh.write(f"body<<{delim}\n{body}\n{delim}\n")


def main() -> int:
    action_conclusion = os.environ.get("FUZE_ACTION_CONCLUSION", "")
    result_text = os.environ.get("FUZE_RESULT_TEXT", "")
    nonce = os.environ.get("FUZE_VERDICT_NONCE", "")
    mode = os.environ.get("FUZE_ACTION_MODE", "")
    vendor = os.environ.get("FUZE_ACTION_VENDOR", "")
    sensitive_raw = os.environ.get("FUZE_SENSITIVE_FILES", "")
    sensitive_files = [line for line in sensitive_raw.splitlines() if line.strip()]
    job_result = os.environ.get("FUZE_REVIEW_JOB_RESULT", "")
    ready = os.environ.get("FUZE_REVIEW_READY", "")
    availability = os.environ.get("FUZE_ACTION_AVAILABILITY", "")

    result = decide(action_conclusion, result_text, nonce, sensitive_files, mode,
                    job_result, ready, availability)
    body = render_body(result, mode, vendor)

    print(
        f"::notice title=fuze-code-review::decision={result['decision']} "
        f"check={check_for(result)} reason={result['reason']}"
    )
    _write_github_output(result, body)

    return 0


if __name__ == "__main__":
    sys.exit(main())
