global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'robot-catalog-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Robot Catalog Application Metrics
  - job_name: 'robot-catalog-crawler'
    static_configs:
      - targets: ['robot-crawler:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # MongoDB Metrics (if we add mongodb_exporter)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s
    scrape_timeout: 10s
    # This target will be available if we add MongoDB exporter

  # Application Health Check Endpoint
  - job_name: 'robot-catalog-health'
    static_configs:
      - targets: ['robot-crawler:8080']
    scrape_interval: 30s
    metrics_path: /health
    scrape_timeout: 5s

# Remote write configuration (for long-term storage if needed)
# remote_write:
#   - url: "http://victoria-metrics:8428/api/v1/write"

# Remote read configuration (for querying external data if needed)
# remote_read:
#   - url: "http://victoria-metrics:8428/api/v1/read" 