global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - shared-alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['shared-node-exporter:9100']

  - job_name: 'robot-backend'
    static_configs:
      - targets: ['robot-catalog-crawler:8090']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'kafka'
    static_configs:
      - targets: ['shared-kafka:9092']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['shared-mongodb:27017']

  - job_name: 'redis'
    static_configs:
      - targets: ['shared-redis:6379'] 